-- Pass 9.3: Historical intelligence + public-web research/discovery staging.

CREATE TABLE IF NOT EXISTS "ShowCalibrationRecords" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ShowEventId" bigint NOT NULL REFERENCES "ShowEvents"("Id") ON DELETE CASCADE,
  "Year" integer,
  "PeriodLabel" varchar(160) NOT NULL,
  "VendorName" varchar(220),
  "ActualGross" numeric(12,2),
  "GrossLow" numeric(12,2),
  "GrossHigh" numeric(12,2),
  "Placement" text,
  "Conditions" text,
  "Lesson" text,
  "IsDoNotReturn" boolean NOT NULL DEFAULT false,
  "SourceType" varchar(80) NOT NULL DEFAULT 'OWNER_INTELLIGENCE',
  "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "IX_ShowCalibrationRecords_Event" ON "ShowCalibrationRecords"("ShowEventId","Year");

CREATE TABLE IF NOT EXISTS "ShowDiscoveryLeads" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ShowVendorProfileId" bigint REFERENCES "ShowVendorProfiles"("Id") ON DELETE SET NULL,
  "TargetYear" integer NOT NULL DEFAULT 2027,
  "TargetMonth" integer,
  "Title" varchar(500) NOT NULL,
  "Url" varchar(1600) NOT NULL,
  "Snippet" text,
  "SearchQuery" text,
  "Status" varchar(40) NOT NULL DEFAULT 'NEW',
  "DiscoveredAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowDiscoveryLeads_Url" ON "ShowDiscoveryLeads"("Url");
CREATE INDEX IF NOT EXISTS "IX_ShowDiscoveryLeads_Queue" ON "ShowDiscoveryLeads"("TargetYear","TargetMonth","Status");

-- Permanent event identities learned during calibration. Do not invent exact years when the owner did not provide them.
INSERT INTO "ShowEvents" ("Name","City","State","EventType","Notes","CreatedAt","UpdatedAt")
SELECT v.name,v.city,v.state,v.type,v.notes,NOW(),NOW()
FROM (VALUES
 ('Rockville Covered Bridge Festival','Rockville','IN','HANDMADE_DESTINATION','Parke County Covered Bridge ecosystem — Rockville must be evaluated separately from other bridge towns.'),
 ('Bridgeton Covered Bridge Festival','Bridgeton','IN','HANDMADE_DESTINATION','Parke County Covered Bridge ecosystem — preserve Mill handmade zone intelligence separately from general Bridgeton resale areas.'),
 ('Marshall County Blueberry Festival','Plymouth','IN','CRAFT_FESTIVAL','Historical Ancient Innovations placement is in a poorly visible craft tent; street placement preferred.'),
 ('Seymour Oktoberfest','Seymour','IN','COMMUNITY_FESTIVAL','Strong fall market with matched-vendor calibration data.'),
 ('Cincinnati Summerfair','Cincinnati','OH','JURIED_ART','Ancient Innovations is an accessible-price purchase relative to much of the fine-art marketplace.'),
 ('Dayton Celtic Festival','Dayton','OH','CELTIC_FESTIVAL','Premium niche with proven Ancient Innovations fit.'),
 ('Historic Irvington Halloween Festival','Indianapolis','IN','HOLIDAY_FESTIVAL','One-day high-efficiency fall event.'),
 ('Swiss Wine Festival','Vevay','IN','FOOD_WINE_FESTIVAL','Known severe underperformer for Ancient Innovations; local/regional spending power matters.'),
 ('Hillbilly Days','Pikeville','KY','COMMUNITY_FESTIVAL','Ancient Innovations do-not-return history.'),
 ('Bloomington Handmade Holiday Market','Bloomington','IN','HANDMADE_HOLIDAY','Qualified handmade holiday shoppers; college-market positive.'),
 ('Oak Hills Band Association Fall Craft Fair','Cincinnati','OH','SCHOOL_CRAFT','Low shopper density and weaker spending-power fit.'),
 ('Center Grove Craft Fair','Greenwood','IN','SCHOOL_CRAFT','Placement-sensitive; extreme vendor count causes route completion/wallet depletion risk.'),
 ('Lakota East Holiday Arts & Crafts Show','Liberty Township','OH','SCHOOL_CRAFT','Main Street placement outperformed cafeteria; nearby Lakota West creates cannibalization risk.'),
 ('Appalachian Festival','New Richmond','OH','CULTURAL_CRAFT','Moved from Coney Island to New Richmond; old venue attendance must not be treated as current.'),
 ('Frankfort Fall Festival','Frankfort','IL','HANDMADE_FALL','Prospective calibration test; preserve pre-show forecast.'),
 ('Bucyrus Bratwurst Festival','Bucyrus','OH','FOOD_COMMUNITY_FESTIVAL','Known failure: craft marketplace health and placement contradicted headline attendance.')
) AS v(name,city,state,type,notes)
WHERE NOT EXISTS (SELECT 1 FROM "ShowEvents" e WHERE e."Name"=v.name AND COALESCE(e."City",'')=v.city AND COALESCE(e."State",'')=v.state);

-- Historical/calibration records. PeriodLabel is used instead of guessing a calendar year when it was not supplied.
WITH seed(event_name,city,state,period,vendor,actual,lowv,highv,placement,conditions,lesson,dnr) AS (VALUES
 ('Rockville Covered Bridge Festival','Rockville','IN','Historical proven result','Jaime',17000,NULL,NULL,'Rockville location','200+ notebooks sold. Destination shopping.','Proven $10K+ anchor; event/location level matters.',false),
 ('Bridgeton Covered Bridge Festival','Bridgeton','IN','Owner production hypothesis',NULL,NULL,34000,51000,'Mill handmade area desired','Owner reports 5–10x Rockville attendance and expects 2–3x Rockville sales.','Treat as high-stakes production forecast; qualified zone traffic must be researched, not attendance scaled linearly.',false),
 ('Marshall County Blueberry Festival','Plymouth','IN','Historical range','Jaime',NULL,6000,7500,'Craft tent','Tent obscured by vendors/honey tent; weak signage.','Observed sales may understate show potential due to poor visibility; request street or unobstructed placement.',false),
 ('Seymour Oktoberfest','Seymour','IN','Jaime year','Jaime',9000,NULL,NULL,NULL,NULL,'Strong show baseline.',false),
 ('Seymour Oktoberfest','Seymour','IN','Abby year','Abby Yount',3500,NULL,NULL,NULL,NULL,'Same show produced a much lower result with Abby; vendor effect must remain separate from show quality.',false),
 ('Cincinnati Summerfair','Cincinnati','OH','Historical range','Jaime',NULL,9000,10000,NULL,'Ancient Innovations priced about $70 versus normal $65; still relatively inexpensive within fine-art environment.','Relative price position can be a major positive.',false),
 ('Dayton Celtic Festival','Dayton','OH','Historical result','Jaime',12000,NULL,NULL,NULL,'Approx. $750 booth fee.','Premium niche + healthy marketplace can justify higher fees.',false),
 ('Historic Irvington Halloween Festival','Indianapolis','IN','Historical result','Jaime',5000,NULL,NULL,NULL,'About seven selling hours.','Revenue/hour and opportunity efficiency matter, not just total gross.',false),
 ('Swiss Wine Festival','Vevay','IN','2025 result','Blake',NULL,NULL,1000,NULL,'Actual gross was under $1,000. Rural southeast Indiana local/regional economics were weak for the price point.','Attendance/longevity cannot override weak qualified shopping demand and spending power.',true),
 ('Hillbilly Days','Pikeville','KY','Historical failure','Jaime',NULL,NULL,NULL,'Parking garage','Only recovered booth + hotel; left after Friday. Attendees were exceptionally rude/mean. Neighbor with ~$10 items also was not selling.','Do not return. Qualified shopping behavior/crowd culture/placement can overwhelm headline attendance.',true),
 ('Bloomington Handmade Holiday Market','Bloomington','IN','Historical result',NULL,5000,NULL,NULL,NULL,NULL,'Qualified handmade holiday shoppers can outperform much larger raw-attendance events.',false),
 ('Oak Hills Band Association Fall Craft Fair','Cincinnati','OH','Historical result',NULL,1800,NULL,NULL,NULL,'Too few shoppers for vendor count; local market not affluent enough for Ancient Innovations price point.','Shopper/vendor density + feeder-market economics must be screened early.',true),
 ('Center Grove Craft Fair','Greenwood','IN','Abby / Student Activity Center','Abby Yount',3200,NULL,NULL,'Student Activity Center','Neighbor also did poorly. Santa brought attraction traffic, not necessarily qualified shopping traffic. Huge vendor count causes fatigue/budget depletion.','Likely combination of weak zone + route/wallet position + vendor effect; test a better primary-shopping-route placement.',false),
 ('Lakota East Holiday Arts & Crafts Show','Liberty Township','OH','Year 1 cafeteria',NULL,3500,NULL,NULL,'Cafeteria',NULL,'Placement-sensitive.',false),
 ('Lakota East Holiday Arts & Crafts Show','Liberty Township','OH','Year 2 Main Street',NULL,4500,NULL,NULL,'Main Street / Main Hall','Lakota West occurred first; customers reported having already bought there.','Better placement improved result; overlapping feeder-market cannibalization can suppress standalone demand.',false),
 ('Appalachian Festival','New Richmond','OH','New Richmond normal year',NULL,3800,NULL,NULL,'New Richmond',NULL,'Do not import old Coney Island attendance into New Richmond baseline.',false),
 ('Appalachian Festival','New Richmond','OH','Construction/disrupted year',NULL,2500,NULL,NULL,'Relocated due to construction','Attendance hurt by construction plus negative organizer publicity.','Year-specific disruption must be preserved; watch for recovery after redevelopment.',false),
 ('Bucyrus Bratwurst Festival','Bucyrus','OH','2026 observed failure','Jaime',130,NULL,NULL,'Side street/off main flow','Only two notebooks observed in the cited period; craft vendor ecosystem was tiny relative to headline attendance.','Large attendance + weak marketplace ecosystem is an anomaly, not an opportunity.',true)
)
INSERT INTO "ShowCalibrationRecords" ("ShowEventId","PeriodLabel","VendorName","ActualGross","GrossLow","GrossHigh","Placement","Conditions","Lesson","IsDoNotReturn","SourceType","CreatedAt")
SELECT e."Id",s.period,s.vendor,s.actual,s.lowv,s.highv,s.placement,s.conditions,s.lesson,s.dnr,'OWNER_INTELLIGENCE',NOW()
FROM seed s JOIN "ShowEvents" e ON e."Name"=s.event_name AND COALESCE(e."City",'')=s.city AND COALESCE(e."State",'')=s.state
WHERE NOT EXISTS (
  SELECT 1 FROM "ShowCalibrationRecords" c WHERE c."ShowEventId"=e."Id" AND c."PeriodLabel"=s.period AND COALESCE(c."VendorName",'')=COALESCE(s.vendor,'')
);

-- Frankfort: first genuinely prospective calibration. Keep the pre-show prediction immutable.
INSERT INTO "ShowEditions" ("ShowEventId","Year","Status","LeadSource","ResearchStatus","Recommendation","ResearchPriority","LeadNote","MarketplaceQuality","ShoppingIntent","LocalSpendingPower","EventHealth","VendorSaturation","CreatedAt","UpdatedAt")
SELECT e."Id",2026,'CANDIDATE','HISTORICAL','RESEARCH_COMPLETE','STRONG_APPLY','HIGH',
 'Prospective test: Ancient Innovations has not attended yet. Owner/vendor intelligence says shoppers arrive early, identify purchases, and wait until transactions are allowed.',
 'EXCELLENT','EXCEPTIONAL','VERY HIGH','STABLE','HIGH',NOW(),NOW()
FROM "ShowEvents" e WHERE e."Name"='Frankfort Fall Festival' AND e."City"='Frankfort' AND e."State"='IL'
AND NOT EXISTS (SELECT 1 FROM "ShowEditions" se WHERE se."ShowEventId"=e."Id" AND se."Year"=2026);

INSERT INTO "ShowForecasts" ("ShowEditionId","ShowVendorProfileId","ForecastLow","ForecastHigh","ExpectedGross","ProductionTarget","TenKPotential","StockoutRisk","PositiveFactors","NegativeFactors","Unknowns","Assumptions","Confidence","EvidenceSummary","FrozenAt")
SELECT se."Id",v."Id",12000,18000,14000,18000,'STRONGLY SUPPORTED','HIGH',
 'Handmade enforcement; exceptional local spending power; strong qualified shopping behavior; fall timing; Jaime selling; A-/B+ placement.',
 'High vendor count; exact attendance remains less important/uncertain.',
 'First Ancient Innovations result at this show; exact conversion rate.',
 'Placement remains approximately A-/B+ and inventory is sufficient to avoid stockouts.',
 'MODERATE-HIGH',
 'Frozen prospective forecast before Ancient Innovations attendance: expected $12K-$16K with $18K+ upside. Database range stores $12K-$18K so the upside is not lost; expected midpoint $14K; production target at least $18K.',NOW()
FROM "ShowEditions" se
JOIN "ShowEvents" e ON e."Id"=se."ShowEventId"
LEFT JOIN "ShowVendorProfiles" v ON v."VendorName"='Jaime'
WHERE e."Name"='Frankfort Fall Festival' AND se."Year"=2026
AND NOT EXISTS (SELECT 1 FROM "ShowForecasts" f WHERE f."ShowEditionId"=se."Id");

INSERT INTO "ShowResearchEvidence" ("ShowEditionId","EvidenceType","SourceName","AppliesToYear","Finding","Reliability","Sentiment","ResearchedAt")
SELECT se."Id",'VENDOR_REPORT','Owner/vendor intelligence',2026,
 'Multiple vendor reports: have booth open by 8; shoppers arrive before transactions are allowed, identify purchases, and wait until payment can be taken. This is high-qualified-shopping-intent evidence.',
 'HIGH','POSITIVE',NOW()
FROM "ShowEditions" se JOIN "ShowEvents" e ON e."Id"=se."ShowEventId"
WHERE e."Name"='Frankfort Fall Festival' AND se."Year"=2026
AND NOT EXISTS (SELECT 1 FROM "ShowResearchEvidence" r WHERE r."ShowEditionId"=se."Id" AND r."SourceName"='Owner/vendor intelligence');
