ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "AudienceOrigin" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "LocalSpendingPower" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "DestinationTourism" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "ShoppingIntent" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "EventHealth" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "MarketplaceQuality" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "VendorSaturation" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "CannibalizationRisk" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "CurrentDisruptions" text;
ALTER TABLE "ShowEditions" ADD COLUMN IF NOT EXISTS "FutureLocationRequest" text;
ALTER TABLE "ShowForecasts" ADD COLUMN IF NOT EXISTS "ExpectedGross" numeric(12,2);
ALTER TABLE "ShowForecasts" ADD COLUMN IF NOT EXISTS "ProductionTarget" numeric(12,2);
ALTER TABLE "ShowForecasts" ADD COLUMN IF NOT EXISTS "TenKPotential" text;
ALTER TABLE "ShowForecasts" ADD COLUMN IF NOT EXISTS "StockoutRisk" text;
ALTER TABLE "ShowForecasts" ADD COLUMN IF NOT EXISTS "PositiveFactors" text;
ALTER TABLE "ShowForecasts" ADD COLUMN IF NOT EXISTS "NegativeFactors" text;
ALTER TABLE "ShowForecasts" ADD COLUMN IF NOT EXISTS "Unknowns" text;
ALTER TABLE "ShowForecasts" ADD COLUMN IF NOT EXISTS "Assumptions" text;
ALTER TABLE "ShowResults" ADD COLUMN IF NOT EXISTS "VendorCommission" numeric(12,2);
ALTER TABLE "ShowResults" ADD COLUMN IF NOT EXISTS "SellingHours" numeric(12,2);
ALTER TABLE "ShowResults" ADD COLUMN IF NOT EXISTS "RevenuePerHour" numeric(12,2);
ALTER TABLE "ShowResults" ADD COLUMN IF NOT EXISTS "InventoryBrought" text;
ALTER TABLE "ShowResults" ADD COLUMN IF NOT EXISTS "Stockouts" text;
ALTER TABLE "ShowResults" ADD COLUMN IF NOT EXISTS "PlacementGrade" text;
ALTER TABLE "ShowResults" ADD COLUMN IF NOT EXISTS "ReturningCustomerNotes" text;
CREATE TABLE IF NOT EXISTS "ShowLocations" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ShowEventId" bigint NOT NULL REFERENCES "ShowEvents"("Id") ON DELETE CASCADE,
  "Name" varchar(240) NOT NULL,
  "ParentLocationName" text, "MarketplaceQuality" text, "HandmadeConcentration" text,
  "QualifiedTraffic" text, "RouteCompletion" text, "WalletPosition" text,
  "PreferredPlacement" text, "AvoidPlacement" text, "Notes" text
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowLocations_ShowEventId_Name" ON "ShowLocations"("ShowEventId","Name");
CREATE TABLE IF NOT EXISTS "ShowMaps" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE CASCADE,
  "Year" integer NOT NULL, "Title" varchar(300) NOT NULL, "MapType" varchar(80) NOT NULL,
  "OriginalFileName" text, "StoredFileName" text, "SourceUrl" text, "LocationName" text, "ZoneName" text,
  "BoothNumber" text, "PlacementGrade" text, "QualifiedTraffic" text, "RouteCompletion" text, "WalletPosition" text,
  "Entrances" text, "PrimaryRoute" text, "Attractions" text, "Obstructions" text, "PreferredAreas" text, "AvoidAreas" text,
  "Notes" text, "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "IX_ShowMaps_ShowEditionId_Year" ON "ShowMaps"("ShowEditionId","Year");
CREATE TABLE IF NOT EXISTS "ShowLearnings" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE CASCADE,
  "ShowForecastId" bigint, "ActualGross" numeric(12,2), "DollarVariance" numeric(12,2), "PercentVariance" numeric(8,2),
  "InsideForecastRange" boolean, "Conditions" text, "VarianceExplanation" text, "Lesson" text,
  "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "IX_ShowLearnings_ShowEditionId" ON "ShowLearnings"("ShowEditionId");
