CREATE TABLE IF NOT EXISTS "ArtworkSubcategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ArtworkKey" character varying(300) NOT NULL,
    "ArtworkName" character varying(300) NOT NULL,
    "Subcategory" character varying(80) NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ArtworkSubcategories_ArtworkKey"
    ON "ArtworkSubcategories" ("ArtworkKey");
