CREATE TABLE IF NOT EXISTS "InventoryHolds" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "HoldKey" character varying(500) NOT NULL,
    "ItemName" character varying(300) NOT NULL,
    "OriginalCategory" character varying(160) NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_InventoryHolds_HoldKey"
ON "InventoryHolds" ("HoldKey");
