-- Ancient Innovations Brain Core B2 — idempotent schema
-- Includes B1 governance tables so a fresh/partially repaired B1 is safe to upgrade.
CREATE TABLE IF NOT EXISTS "BrainAgentProfiles" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AgentKey" varchar(80) NOT NULL, "DisplayName" varchar(160) NOT NULL,
  "Purpose" varchar(2000) NOT NULL, "ArmScope" varchar(120) NOT NULL,
  "RuntimeKind" varchar(120) NOT NULL, "AutonomyLevel" varchar(80) NOT NULL,
  "Enabled" boolean NOT NULL DEFAULT TRUE, "CreatedAt" timestamptz NOT NULL,
  "UpdatedAt" timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BrainAgentProfiles_AgentKey" ON "BrainAgentProfiles" ("AgentKey");

CREATE TABLE IF NOT EXISTS "BrainCapabilityGrants" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AgentKey" varchar(80) NOT NULL, "CapabilityKey" varchar(200) NOT NULL,
  "AccessMode" varchar(40) NOT NULL, "RequiresHumanApproval" boolean NOT NULL DEFAULT FALSE,
  "BoundaryNote" varchar(2000) NULL, "UpdatedAt" timestamptz NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BrainCapabilityGrants_AgentKey_CapabilityKey" ON "BrainCapabilityGrants" ("AgentKey", "CapabilityKey");

CREATE TABLE IF NOT EXISTS "BrainAuditEvents" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AgentKey" varchar(80) NOT NULL, "EventType" varchar(100) NOT NULL,
  "TargetArm" varchar(120) NOT NULL, "ActionKey" varchar(200) NOT NULL,
  "Outcome" varchar(80) NOT NULL, "Rationale" varchar(4000) NULL,
  "CorrelationId" varchar(160) NULL, "OccurredAt" timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_BrainAuditEvents_OccurredAt" ON "BrainAuditEvents" ("OccurredAt");
CREATE INDEX IF NOT EXISTS "IX_BrainAuditEvents_AgentKey" ON "BrainAuditEvents" ("AgentKey");

CREATE TABLE IF NOT EXISTS "BrainMemoryItems" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MemoryKey" varchar(80) NOT NULL, "MemoryType" varchar(40) NOT NULL,
  "ArmScope" varchar(120) NOT NULL, "SubjectType" varchar(120) NULL,
  "SubjectKey" varchar(240) NULL, "Title" varchar(300) NOT NULL,
  "Content" text NOT NULL, "Status" varchar(40) NOT NULL,
  "Confidence" numeric(5,4) NOT NULL, "SourceType" varchar(80) NOT NULL,
  "SourceRef" varchar(1000) NULL, "EvidenceSummary" text NULL,
  "CreatedBy" varchar(120) NOT NULL, "SupersedesMemoryId" bigint NULL,
  "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz NOT NULL,
  "LastConfirmedAt" timestamptz NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BrainMemoryItems_MemoryKey" ON "BrainMemoryItems" ("MemoryKey");
CREATE INDEX IF NOT EXISTS "IX_BrainMemoryItems_ArmScope_SubjectType_SubjectKey" ON "BrainMemoryItems" ("ArmScope", "SubjectType", "SubjectKey");
CREATE INDEX IF NOT EXISTS "IX_BrainMemoryItems_MemoryType_Status" ON "BrainMemoryItems" ("MemoryType", "Status");
CREATE INDEX IF NOT EXISTS "IX_BrainMemoryItems_UpdatedAt" ON "BrainMemoryItems" ("UpdatedAt");

CREATE TABLE IF NOT EXISTS "BrainDecisionRecords" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DecisionKey" varchar(80) NOT NULL, "AgentKey" varchar(80) NOT NULL,
  "ArmScope" varchar(120) NOT NULL, "SubjectType" varchar(120) NULL,
  "SubjectKey" varchar(240) NULL, "DecisionType" varchar(100) NOT NULL,
  "Recommendation" text NOT NULL, "RecommendationReasoning" text NULL,
  "RecommendationConfidence" numeric(5,4) NULL, "HumanDecision" text NULL,
  "HumanReasoning" text NULL, "Outcome" text NULL, "OutcomeNotes" text NULL,
  "RecommendedAt" timestamptz NOT NULL, "DecidedAt" timestamptz NULL,
  "OutcomeRecordedAt" timestamptz NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BrainDecisionRecords_DecisionKey" ON "BrainDecisionRecords" ("DecisionKey");
CREATE INDEX IF NOT EXISTS "IX_BrainDecisionRecords_ArmScope_SubjectType_SubjectKey" ON "BrainDecisionRecords" ("ArmScope", "SubjectType", "SubjectKey");
CREATE INDEX IF NOT EXISTS "IX_BrainDecisionRecords_RecommendedAt" ON "BrainDecisionRecords" ("RecommendedAt");

CREATE TABLE IF NOT EXISTS "BrainLearningCandidates" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LearningKey" varchar(80) NOT NULL, "AgentKey" varchar(80) NOT NULL,
  "ArmScope" varchar(120) NOT NULL, "SubjectType" varchar(120) NULL,
  "SubjectKey" varchar(240) NULL, "ProposedLesson" text NOT NULL,
  "Reasoning" text NULL, "EvidenceRefs" text NULL,
  "Confidence" numeric(5,4) NOT NULL, "Status" varchar(40) NOT NULL,
  "ReviewReason" text NULL, "PromotedMemoryId" bigint NULL,
  "CreatedAt" timestamptz NOT NULL, "ReviewedAt" timestamptz NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BrainLearningCandidates_LearningKey" ON "BrainLearningCandidates" ("LearningKey");
CREATE INDEX IF NOT EXISTS "IX_BrainLearningCandidates_Status_CreatedAt" ON "BrainLearningCandidates" ("Status", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_BrainLearningCandidates_ArmScope_SubjectType_SubjectKey" ON "BrainLearningCandidates" ("ArmScope", "SubjectType", "SubjectKey");

CREATE TABLE IF NOT EXISTS "BrainContradictions" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MemoryAId" bigint NOT NULL, "MemoryBId" bigint NOT NULL,
  "Description" text NOT NULL, "Status" varchar(40) NOT NULL,
  "DetectedBy" varchar(120) NOT NULL, "Resolution" text NULL,
  "ResolvedBy" varchar(120) NULL, "CreatedAt" timestamptz NOT NULL,
  "ResolvedAt" timestamptz NULL
);
CREATE INDEX IF NOT EXISTS "IX_BrainContradictions_Status_CreatedAt" ON "BrainContradictions" ("Status", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_BrainContradictions_MemoryAId" ON "BrainContradictions" ("MemoryAId");
CREATE INDEX IF NOT EXISTS "IX_BrainContradictions_MemoryBId" ON "BrainContradictions" ("MemoryBId");
