-- Ancient Innovations Control App v10 Pass 9 - Show Arm foundation
CREATE TABLE IF NOT EXISTS "ShowEvents" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" varchar(240) NOT NULL, "PromoterName" varchar(240), "City" varchar(120), "State" varchar(80), "EventType" varchar(100), "WebsiteUrl" varchar(1000), "IsHardExcluded" boolean NOT NULL DEFAULT false, "ExclusionReason" varchar(1000), "Notes" text, "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowEvents_Name_City_State" ON "ShowEvents" ("Name","City","State");

CREATE TABLE IF NOT EXISTS "ShowEditions" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ShowEventId" bigint NOT NULL REFERENCES "ShowEvents"("Id") ON DELETE CASCADE, "Year" integer NOT NULL, "StartDate" date, "EndDate" date, "Status" varchar(40) NOT NULL, "JuryFee" numeric(12,2), "BoothFee" numeric(12,2), "ClaimedAttendance" integer, "VerifiedAttendance" integer, "VendorCount" integer, "HandmadeVendorCount" integer, "ApplicationOpenDate" date, "ApplicationDeadline" date, "AcceptanceDate" date, "BoothPaymentDeadline" date, "ShowHours" text, "SetupDetails" text, "BoothOptions" text, "SecurityDetails" text, "LoadInDetails" text, "ParkingDetails" text, "CampingDetails" text, "MapUrl" text, "LocationIntel" text, "MarketingIntel" text, "WeatherIntel" text, "Notes" text, "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowEditions_ShowEventId_Year" ON "ShowEditions"("ShowEventId","Year");
CREATE INDEX IF NOT EXISTS "IX_ShowEditions_StartDate" ON "ShowEditions"("StartDate");

CREATE TABLE IF NOT EXISTS "ShowVendorProfiles" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "VendorName" varchar(220) NOT NULL, "ApplicationUserId" text REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL, "HomeCity" varchar(120), "HomeState" varchar(80), "MaxTravelHours" numeric(5,2), "TargetShowsPerMonth" integer, "MaxShowsPerMonth" integer, "TargetGrossSales" numeric(12,2), "CanCamp" boolean NOT NULL DEFAULT false, "UsuallySolo" boolean NOT NULL DEFAULT false, "IsFullTimeVendor" boolean NOT NULL DEFAULT false, "IsShowAdmin" boolean NOT NULL DEFAULT false, "SchedulingRequirements" text, "SeasonalRequirements" text, "Notes" text, "IsActive" boolean NOT NULL DEFAULT true);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowVendorProfiles_VendorName" ON "ShowVendorProfiles"("VendorName");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowVendorProfiles_ApplicationUserId" ON "ShowVendorProfiles"("ApplicationUserId") WHERE "ApplicationUserId" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "ShowResearchEvidence" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE CASCADE, "EvidenceType" varchar(80) NOT NULL, "SourceName" varchar(300), "SourceUrl" varchar(1200), "SourceDate" date, "AppliesToYear" integer, "Finding" text NOT NULL, "Reliability" varchar(40) NOT NULL, "Sentiment" varchar(40) NOT NULL, "ResearchedAt" timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS "IX_ShowResearchEvidence_ShowEditionId_EvidenceType" ON "ShowResearchEvidence"("ShowEditionId","EvidenceType");

CREATE TABLE IF NOT EXISTS "ShowOpportunities" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE CASCADE, "ShowVendorProfileId" bigint NOT NULL REFERENCES "ShowVendorProfiles"("Id") ON DELETE RESTRICT, "Priority" varchar(8) NOT NULL, "Status" varchar(40) NOT NULL, "ForecastLow" numeric(12,2), "ForecastHigh" numeric(12,2), "ForecastConfidence" varchar(40) NOT NULL, "FitRationale" text, "CreatedAt" timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS "IX_ShowOpportunities_ShowEditionId_ShowVendorProfileId_Priority" ON "ShowOpportunities"("ShowEditionId","ShowVendorProfileId","Priority");

CREATE TABLE IF NOT EXISTS "ShowAssignments" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE CASCADE, "ShowVendorProfileId" bigint NOT NULL REFERENCES "ShowVendorProfiles"("Id") ON DELETE RESTRICT, "Status" varchar(40) NOT NULL, "OfferedAt" timestamptz NOT NULL, "RespondedAt" timestamptz, "DeclineReason" text, "CommittedAt" timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowAssignments_ShowEditionId_ShowVendorProfileId" ON "ShowAssignments"("ShowEditionId","ShowVendorProfileId");

CREATE TABLE IF NOT EXISTS "ShowApplications" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE CASCADE, "ShowVendorProfileId" bigint REFERENCES "ShowVendorProfiles"("Id") ON DELETE SET NULL, "Status" varchar(40) NOT NULL, "AppliedAt" timestamptz, "DecisionAt" timestamptz, "JuryFeePaid" numeric(12,2), "BoothFeePaid" numeric(12,2), "LocationPreferenceRecommended" text, "LocationPreferenceRequested" text, "AssignedLocation" text, "Notes" text);
CREATE INDEX IF NOT EXISTS "IX_ShowApplications_ShowEditionId" ON "ShowApplications"("ShowEditionId");

CREATE TABLE IF NOT EXISTS "ShowForecasts" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE CASCADE, "ShowVendorProfileId" bigint REFERENCES "ShowVendorProfiles"("Id") ON DELETE SET NULL, "ForecastLow" numeric(12,2) NOT NULL, "ForecastHigh" numeric(12,2) NOT NULL, "Confidence" varchar(40) NOT NULL, "EvidenceSummary" text, "FrozenAt" timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS "IX_ShowForecasts_ShowEditionId_FrozenAt" ON "ShowForecasts"("ShowEditionId","FrozenAt");

CREATE TABLE IF NOT EXISTS "ShowResults" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE CASCADE, "ShowVendorProfileId" bigint NOT NULL REFERENCES "ShowVendorProfiles"("Id") ON DELETE RESTRICT, "GrossSquareSales" numeric(12,2) NOT NULL, "BoothExpense" numeric(12,2), "HotelExpense" numeric(12,2), "TravelExpense" numeric(12,2), "OtherExpense" numeric(12,2), "ActualWeather" text, "ActualBoothLocation" text, "CrowdNotes" text, "Problems" text, "WouldReturn" boolean, "ReturnReason" text, "RecordedAt" timestamptz NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowResults_ShowEditionId_ShowVendorProfileId" ON "ShowResults"("ShowEditionId","ShowVendorProfileId");

CREATE TABLE IF NOT EXISTS "ShowTours" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" varchar(240) NOT NULL, "StartDate" date, "EndDate" date, "Region" varchar(240), "Status" varchar(40) NOT NULL, "Notes" text);
CREATE TABLE IF NOT EXISTS "ShowTourStops" (
 "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ShowTourId" bigint NOT NULL REFERENCES "ShowTours"("Id") ON DELETE CASCADE, "ShowEditionId" bigint NOT NULL REFERENCES "ShowEditions"("Id") ON DELETE RESTRICT, "Sequence" integer NOT NULL, "IsAnchor" boolean NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowTourStops_ShowTourId_Sequence" ON "ShowTourStops"("ShowTourId","Sequence");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ShowTourStops_ShowTourId_ShowEditionId" ON "ShowTourStops"("ShowTourId","ShowEditionId");
