--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6 (Debian 17.6-2.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-2.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ShowApplications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowApplications" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint,
    "Status" character varying(40) NOT NULL,
    "AppliedAt" timestamp with time zone,
    "DecisionAt" timestamp with time zone,
    "JuryFeePaid" numeric(12,2),
    "BoothFeePaid" numeric(12,2),
    "LocationPreferenceRecommended" text,
    "LocationPreferenceRequested" text,
    "AssignedLocation" text,
    "Notes" text,
    "Platform" character varying(80),
    "ApplicationUrl" character varying(1600),
    "ExternalApplicationId" character varying(240),
    "ExternalStatus" character varying(120),
    "NextAction" character varying(500),
    "LastCheckedAt" timestamp with time zone
);


--
-- Name: ShowApplications_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowApplications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowApplications_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowAssignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowAssignments" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint NOT NULL,
    "Status" character varying(40) NOT NULL,
    "OfferedAt" timestamp with time zone NOT NULL,
    "RespondedAt" timestamp with time zone,
    "DeclineReason" text,
    "CommittedAt" timestamp with time zone
);


--
-- Name: ShowAssignments_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowAssignments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowAssignments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowCalibrationRecords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowCalibrationRecords" (
    "Id" bigint NOT NULL,
    "ShowEventId" bigint NOT NULL,
    "Year" integer,
    "PeriodLabel" character varying(160) NOT NULL,
    "VendorName" character varying(220),
    "ActualGross" numeric(12,2),
    "GrossLow" numeric(12,2),
    "GrossHigh" numeric(12,2),
    "Placement" text,
    "Conditions" text,
    "Lesson" text,
    "IsDoNotReturn" boolean DEFAULT false NOT NULL,
    "SourceType" character varying(80) DEFAULT 'OWNER_INTELLIGENCE'::character varying NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: ShowCalibrationRecords_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowCalibrationRecords" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowCalibrationRecords_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowDiscoveryLeads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowDiscoveryLeads" (
    "Id" bigint NOT NULL,
    "ShowVendorProfileId" bigint,
    "TargetYear" integer DEFAULT 2027 NOT NULL,
    "TargetMonth" integer,
    "Title" character varying(500) NOT NULL,
    "Url" character varying(1600) NOT NULL,
    "Snippet" text,
    "SearchQuery" text,
    "Status" character varying(40) DEFAULT 'NEW'::character varying NOT NULL,
    "DiscoveredAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: ShowDiscoveryLeads_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowDiscoveryLeads" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowDiscoveryLeads_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowDocuments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowDocuments" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint,
    "DocumentType" character varying(80) DEFAULT 'OTHER'::character varying NOT NULL,
    "Title" character varying(500) NOT NULL,
    "StoredPath" text,
    "SourceUrl" text,
    "AppliesToYear" integer,
    "Notes" text,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "ShowVendorProfileId" bigint
);


--
-- Name: ShowDocuments_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."ShowDocuments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ShowDocuments_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."ShowDocuments_Id_seq" OWNED BY public."ShowDocuments"."Id";


--
-- Name: ShowEditions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowEditions" (
    "Id" bigint NOT NULL,
    "ShowEventId" bigint NOT NULL,
    "Year" integer NOT NULL,
    "StartDate" date,
    "EndDate" date,
    "Status" character varying(40) NOT NULL,
    "JuryFee" numeric(12,2),
    "BoothFee" numeric(12,2),
    "ClaimedAttendance" integer,
    "VerifiedAttendance" integer,
    "VendorCount" integer,
    "HandmadeVendorCount" integer,
    "ApplicationOpenDate" date,
    "ApplicationDeadline" date,
    "AcceptanceDate" date,
    "BoothPaymentDeadline" date,
    "ShowHours" text,
    "SetupDetails" text,
    "BoothOptions" text,
    "SecurityDetails" text,
    "LoadInDetails" text,
    "ParkingDetails" text,
    "CampingDetails" text,
    "MapUrl" text,
    "LocationIntel" text,
    "MarketingIntel" text,
    "WeatherIntel" text,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "AudienceOrigin" text,
    "LocalSpendingPower" text,
    "DestinationTourism" text,
    "ShoppingIntent" text,
    "EventHealth" text,
    "MarketplaceQuality" text,
    "VendorSaturation" text,
    "CannibalizationRisk" text,
    "CurrentDisruptions" text,
    "FutureLocationRequest" text,
    "LeadSource" text DEFAULT 'MANUAL'::text NOT NULL,
    "ResearchStatus" text DEFAULT 'NEEDS_RESEARCH'::text NOT NULL,
    "Recommendation" text DEFAULT 'UNDECIDED'::text NOT NULL,
    "ResearchPriority" text DEFAULT 'NORMAL'::text NOT NULL,
    "LeadUrl" text,
    "LeadNote" text,
    "ResearchStartedAt" timestamp with time zone,
    "ResearchCompletedAt" timestamp with time zone
);


--
-- Name: ShowEditions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowEditions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowEditions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowEmailIntakes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowEmailIntakes" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint,
    "FromAddress" text,
    "Subject" text,
    "BodyText" text,
    "MessageDate" timestamp with time zone,
    "Status" character varying(40) DEFAULT 'NEEDS_REVIEW'::character varying NOT NULL,
    "MatchNotes" text,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "ExternalMessageId" character varying(500),
    "ToAddress" text,
    "Route" character varying(80) DEFAULT 'UNKNOWN'::character varying NOT NULL,
    "AttachmentSummary" text,
    "MailboxAddress" character varying(320),
    "BrainSummary" text,
    "ActionSummary" text,
    "IsProtectedSender" boolean DEFAULT false NOT NULL,
    "UnsubscribeUrl" text,
    "UnsubscribeRecommended" boolean DEFAULT false NOT NULL
);


--
-- Name: ShowEmailIntakes_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."ShowEmailIntakes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ShowEmailIntakes_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."ShowEmailIntakes_Id_seq" OWNED BY public."ShowEmailIntakes"."Id";


--
-- Name: ShowEvents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowEvents" (
    "Id" bigint NOT NULL,
    "Name" character varying(240) NOT NULL,
    "PromoterName" character varying(240),
    "City" character varying(120),
    "State" character varying(80),
    "EventType" character varying(100),
    "WebsiteUrl" character varying(1000),
    "IsHardExcluded" boolean DEFAULT false NOT NULL,
    "ExclusionReason" character varying(1000),
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


--
-- Name: ShowEvents_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowEvents" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowEvents_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowFinancialReferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowFinancialReferences" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint,
    "Kind" character varying(40) DEFAULT 'EXPENSE'::character varying NOT NULL,
    "Category" character varying(80) DEFAULT 'OTHER'::character varying NOT NULL,
    "Amount" numeric NOT NULL,
    "Reimbursable" boolean DEFAULT false NOT NULL,
    "Description" text,
    "ReceiptPath" text,
    "TaxArmExternalKey" character varying(200),
    "RecordedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "ReimbursedAmount" numeric,
    "ReimbursedDate" date
);


--
-- Name: ShowFinancialReferences_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."ShowFinancialReferences_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ShowFinancialReferences_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."ShowFinancialReferences_Id_seq" OWNED BY public."ShowFinancialReferences"."Id";


--
-- Name: ShowForecasts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowForecasts" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint,
    "ForecastLow" numeric(12,2) NOT NULL,
    "ForecastHigh" numeric(12,2) NOT NULL,
    "Confidence" character varying(40) NOT NULL,
    "EvidenceSummary" text,
    "FrozenAt" timestamp with time zone NOT NULL,
    "ExpectedGross" numeric(12,2),
    "ProductionTarget" numeric(12,2),
    "TenKPotential" text,
    "StockoutRisk" text,
    "PositiveFactors" text,
    "NegativeFactors" text,
    "Unknowns" text,
    "Assumptions" text
);


--
-- Name: ShowForecasts_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowForecasts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowForecasts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowLearnings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowLearnings" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowForecastId" bigint,
    "ActualGross" numeric(12,2),
    "DollarVariance" numeric(12,2),
    "PercentVariance" numeric(8,2),
    "InsideForecastRange" boolean,
    "Conditions" text,
    "VarianceExplanation" text,
    "Lesson" text,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: ShowLearnings_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowLearnings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowLearnings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowLocations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowLocations" (
    "Id" bigint NOT NULL,
    "ShowEventId" bigint NOT NULL,
    "Name" character varying(240) NOT NULL,
    "ParentLocationName" text,
    "MarketplaceQuality" text,
    "HandmadeConcentration" text,
    "QualifiedTraffic" text,
    "RouteCompletion" text,
    "WalletPosition" text,
    "PreferredPlacement" text,
    "AvoidPlacement" text,
    "Notes" text
);


--
-- Name: ShowLocations_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowLocations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowLocations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowMaps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowMaps" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "Year" integer NOT NULL,
    "Title" character varying(300) NOT NULL,
    "MapType" character varying(80) NOT NULL,
    "OriginalFileName" text,
    "StoredFileName" text,
    "SourceUrl" text,
    "LocationName" text,
    "ZoneName" text,
    "BoothNumber" text,
    "PlacementGrade" text,
    "QualifiedTraffic" text,
    "RouteCompletion" text,
    "WalletPosition" text,
    "Entrances" text,
    "PrimaryRoute" text,
    "Attractions" text,
    "Obstructions" text,
    "PreferredAreas" text,
    "AvoidAreas" text,
    "Notes" text,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: ShowMaps_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowMaps" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowMaps_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowNotes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowNotes" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint,
    "NoteType" character varying(40) DEFAULT 'VENDOR'::character varying NOT NULL,
    "NoteText" text NOT NULL,
    "UseForShowArm" boolean DEFAULT true NOT NULL,
    "UseForMarketing" boolean DEFAULT false NOT NULL,
    "CreatedBy" character varying(220),
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ShowNotes_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowNotes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowNotes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowOpportunities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowOpportunities" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint NOT NULL,
    "Priority" character varying(8) NOT NULL,
    "Status" character varying(40) NOT NULL,
    "ForecastLow" numeric(12,2),
    "ForecastHigh" numeric(12,2),
    "ForecastConfidence" character varying(40) NOT NULL,
    "FitRationale" text,
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: ShowOpportunities_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowOpportunities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowOpportunities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowOrderFulfillments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowOrderFulfillments" (
    "SquareOrderId" character varying(192) NOT NULL,
    "LineItemUid" character varying(192) NOT NULL,
    "Status" character varying(40) DEFAULT 'Needs Production'::character varying NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ShowResearchEvidence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowResearchEvidence" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "EvidenceType" character varying(80) NOT NULL,
    "SourceName" character varying(300),
    "SourceUrl" character varying(1200),
    "SourceDate" date,
    "AppliesToYear" integer,
    "Finding" text NOT NULL,
    "Reliability" character varying(40) NOT NULL,
    "Sentiment" character varying(40) NOT NULL,
    "ResearchedAt" timestamp with time zone NOT NULL
);


--
-- Name: ShowResearchEvidence_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowResearchEvidence" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowResearchEvidence_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowResearchGaps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowResearchGaps" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "GapType" character varying(80) NOT NULL,
    "Description" text NOT NULL,
    "Status" character varying(40) DEFAULT 'OPEN'::character varying NOT NULL,
    "FirstSeenAt" timestamp with time zone DEFAULT now() NOT NULL,
    "LastCheckedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "ResolvedAt" timestamp with time zone,
    "NextCheckAt" timestamp with time zone
);


--
-- Name: ShowResearchGaps_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowResearchGaps" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowResearchGaps_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowResearchRuns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowResearchRuns" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "Trigger" character varying(40) DEFAULT 'MANUAL'::character varying NOT NULL,
    "ResultStatus" character varying(60) DEFAULT 'STARTED'::character varying NOT NULL,
    "EvidenceAdded" integer DEFAULT 0 NOT NULL,
    "OpenGapCount" integer DEFAULT 0 NOT NULL,
    "RecommendationBefore" character varying(60),
    "RecommendationAfter" character varying(60),
    "NextAction" text,
    "Summary" text,
    "StartedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "CompletedAt" timestamp with time zone
);


--
-- Name: ShowResearchRuns_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowResearchRuns" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowResearchRuns_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowResults; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowResults" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint NOT NULL,
    "GrossSquareSales" numeric(12,2) NOT NULL,
    "BoothExpense" numeric(12,2),
    "HotelExpense" numeric(12,2),
    "TravelExpense" numeric(12,2),
    "OtherExpense" numeric(12,2),
    "ActualWeather" text,
    "ActualBoothLocation" text,
    "CrowdNotes" text,
    "Problems" text,
    "WouldReturn" boolean,
    "ReturnReason" text,
    "RecordedAt" timestamp with time zone NOT NULL,
    "VendorCommission" numeric(12,2),
    "SellingHours" numeric(12,2),
    "RevenuePerHour" numeric(12,2),
    "InventoryBrought" text,
    "Stockouts" text,
    "PlacementGrade" text,
    "ReturningCustomerNotes" text
);


--
-- Name: ShowResults_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowResults" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowResults_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowTourStops; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowTourStops" (
    "Id" bigint NOT NULL,
    "ShowTourId" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "Sequence" integer NOT NULL,
    "IsAnchor" boolean DEFAULT false NOT NULL
);


--
-- Name: ShowTourStops_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowTourStops" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowTourStops_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowTours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowTours" (
    "Id" bigint NOT NULL,
    "Name" character varying(240) NOT NULL,
    "StartDate" date,
    "EndDate" date,
    "Region" character varying(240),
    "Status" character varying(40) NOT NULL,
    "Notes" text
);


--
-- Name: ShowTours_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowTours" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowTours_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowVendorAssessments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowVendorAssessments" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint NOT NULL,
    "FitScore" integer DEFAULT 0 NOT NULL,
    "DriveHours" numeric(7,2),
    "DriveMiles" numeric(9,2),
    "TravelFit" character varying(40) DEFAULT 'UNKNOWN'::character varying NOT NULL,
    "Recommendation" character varying(60) DEFAULT 'RESEARCH'::character varying NOT NULL,
    "Rationale" text,
    "CalculatedAt" timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ShowVendorAssessments_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowVendorAssessments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowVendorAssessments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowVendorCloseouts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowVendorCloseouts" (
    "Id" bigint NOT NULL,
    "ShowEditionId" bigint NOT NULL,
    "ShowVendorProfileId" bigint NOT NULL,
    "VendorTrackedSales" numeric,
    "SystemSquareSales" numeric,
    "CommissionRate" numeric,
    "CommissionEarned" numeric,
    "CommissionPaid" numeric,
    "CommissionPaidDate" date,
    "MileageReported" numeric,
    "VendorNotes" text,
    "ClosedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "CloseoutStatus" character varying(40) DEFAULT 'OPEN'::character varying
);


--
-- Name: ShowVendorCloseouts_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."ShowVendorCloseouts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: ShowVendorCloseouts_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."ShowVendorCloseouts_Id_seq" OWNED BY public."ShowVendorCloseouts"."Id";


--
-- Name: ShowVendorProfiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShowVendorProfiles" (
    "Id" bigint NOT NULL,
    "VendorName" character varying(220) NOT NULL,
    "ApplicationUserId" text,
    "HomeCity" character varying(120),
    "HomeState" character varying(80),
    "MaxTravelHours" numeric(5,2),
    "TargetShowsPerMonth" integer,
    "MaxShowsPerMonth" integer,
    "TargetGrossSales" numeric(12,2),
    "CanCamp" boolean DEFAULT false NOT NULL,
    "UsuallySolo" boolean DEFAULT false NOT NULL,
    "IsFullTimeVendor" boolean DEFAULT false NOT NULL,
    "IsShowAdmin" boolean DEFAULT false NOT NULL,
    "SchedulingRequirements" text,
    "SeasonalRequirements" text,
    "Notes" text,
    "IsActive" boolean DEFAULT true NOT NULL
);


--
-- Name: ShowVendorProfiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShowVendorProfiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShowVendorProfiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShowDocuments Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowDocuments" ALTER COLUMN "Id" SET DEFAULT nextval('public."ShowDocuments_Id_seq"'::regclass);


--
-- Name: ShowEmailIntakes Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowEmailIntakes" ALTER COLUMN "Id" SET DEFAULT nextval('public."ShowEmailIntakes_Id_seq"'::regclass);


--
-- Name: ShowFinancialReferences Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowFinancialReferences" ALTER COLUMN "Id" SET DEFAULT nextval('public."ShowFinancialReferences_Id_seq"'::regclass);


--
-- Name: ShowVendorCloseouts Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowVendorCloseouts" ALTER COLUMN "Id" SET DEFAULT nextval('public."ShowVendorCloseouts_Id_seq"'::regclass);


--
-- Name: ShowOrderFulfillments PK_ShowOrderFulfillments; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowOrderFulfillments"
    ADD CONSTRAINT "PK_ShowOrderFulfillments" PRIMARY KEY ("SquareOrderId", "LineItemUid");


--
-- Name: ShowApplications ShowApplications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowApplications"
    ADD CONSTRAINT "ShowApplications_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowAssignments ShowAssignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowAssignments"
    ADD CONSTRAINT "ShowAssignments_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowCalibrationRecords ShowCalibrationRecords_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowCalibrationRecords"
    ADD CONSTRAINT "ShowCalibrationRecords_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowDiscoveryLeads ShowDiscoveryLeads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowDiscoveryLeads"
    ADD CONSTRAINT "ShowDiscoveryLeads_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowDocuments ShowDocuments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowDocuments"
    ADD CONSTRAINT "ShowDocuments_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowEditions ShowEditions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowEditions"
    ADD CONSTRAINT "ShowEditions_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowEmailIntakes ShowEmailIntakes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowEmailIntakes"
    ADD CONSTRAINT "ShowEmailIntakes_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowEvents ShowEvents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowEvents"
    ADD CONSTRAINT "ShowEvents_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowFinancialReferences ShowFinancialReferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowFinancialReferences"
    ADD CONSTRAINT "ShowFinancialReferences_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowForecasts ShowForecasts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowForecasts"
    ADD CONSTRAINT "ShowForecasts_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowLearnings ShowLearnings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowLearnings"
    ADD CONSTRAINT "ShowLearnings_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowLocations ShowLocations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowLocations"
    ADD CONSTRAINT "ShowLocations_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowMaps ShowMaps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowMaps"
    ADD CONSTRAINT "ShowMaps_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowNotes ShowNotes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowNotes"
    ADD CONSTRAINT "ShowNotes_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowOpportunities ShowOpportunities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowOpportunities"
    ADD CONSTRAINT "ShowOpportunities_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowResearchEvidence ShowResearchEvidence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResearchEvidence"
    ADD CONSTRAINT "ShowResearchEvidence_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowResearchGaps ShowResearchGaps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResearchGaps"
    ADD CONSTRAINT "ShowResearchGaps_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowResearchRuns ShowResearchRuns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResearchRuns"
    ADD CONSTRAINT "ShowResearchRuns_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowResults ShowResults_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResults"
    ADD CONSTRAINT "ShowResults_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowTourStops ShowTourStops_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowTourStops"
    ADD CONSTRAINT "ShowTourStops_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowTours ShowTours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowTours"
    ADD CONSTRAINT "ShowTours_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowVendorAssessments ShowVendorAssessments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowVendorAssessments"
    ADD CONSTRAINT "ShowVendorAssessments_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowVendorCloseouts ShowVendorCloseouts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowVendorCloseouts"
    ADD CONSTRAINT "ShowVendorCloseouts_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowVendorProfiles ShowVendorProfiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowVendorProfiles"
    ADD CONSTRAINT "ShowVendorProfiles_pkey" PRIMARY KEY ("Id");


--
-- Name: ShowResearchGaps UQ_ShowResearchGaps_Edition_Type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResearchGaps"
    ADD CONSTRAINT "UQ_ShowResearchGaps_Edition_Type" UNIQUE ("ShowEditionId", "GapType");


--
-- Name: ShowVendorAssessments UQ_ShowVendorAssessments_Edition_Vendor; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowVendorAssessments"
    ADD CONSTRAINT "UQ_ShowVendorAssessments_Edition_Vendor" UNIQUE ("ShowEditionId", "ShowVendorProfileId");


--
-- Name: IX_ShowApplications_ShowEditionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowApplications_ShowEditionId" ON public."ShowApplications" USING btree ("ShowEditionId");


--
-- Name: IX_ShowAssignments_ShowEditionId_ShowVendorProfileId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowAssignments_ShowEditionId_ShowVendorProfileId" ON public."ShowAssignments" USING btree ("ShowEditionId", "ShowVendorProfileId");


--
-- Name: IX_ShowCalibrationRecords_Event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowCalibrationRecords_Event" ON public."ShowCalibrationRecords" USING btree ("ShowEventId", "Year");


--
-- Name: IX_ShowDiscoveryLeads_Queue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowDiscoveryLeads_Queue" ON public."ShowDiscoveryLeads" USING btree ("TargetYear", "TargetMonth", "Status");


--
-- Name: IX_ShowDiscoveryLeads_VendorMonthUrl; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowDiscoveryLeads_VendorMonthUrl" ON public."ShowDiscoveryLeads" USING btree ("ShowVendorProfileId", "TargetYear", "TargetMonth", "Url");


--
-- Name: IX_ShowDiscoveryLeads_Vendor_Year_Month_Url; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowDiscoveryLeads_Vendor_Year_Month_Url" ON public."ShowDiscoveryLeads" USING btree ("ShowVendorProfileId", "TargetYear", "TargetMonth", "Url");


--
-- Name: IX_ShowDocuments_Edition_Vendor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowDocuments_Edition_Vendor" ON public."ShowDocuments" USING btree ("ShowEditionId", "ShowVendorProfileId");


--
-- Name: IX_ShowEditions_Recommendation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowEditions_Recommendation" ON public."ShowEditions" USING btree ("Year", "Recommendation");


--
-- Name: IX_ShowEditions_ResearchStatus; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowEditions_ResearchStatus" ON public."ShowEditions" USING btree ("Year", "ResearchStatus");


--
-- Name: IX_ShowEditions_ShowEventId_Year; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowEditions_ShowEventId_Year" ON public."ShowEditions" USING btree ("ShowEventId", "Year");


--
-- Name: IX_ShowEditions_StartDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowEditions_StartDate" ON public."ShowEditions" USING btree ("StartDate");


--
-- Name: IX_ShowEmailIntakes_ExternalMessageId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowEmailIntakes_ExternalMessageId" ON public."ShowEmailIntakes" USING btree ("ExternalMessageId") WHERE ("ExternalMessageId" IS NOT NULL);


--
-- Name: IX_ShowEmailIntakes_Status_Route; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowEmailIntakes_Status_Route" ON public."ShowEmailIntakes" USING btree ("Status", "Route");


--
-- Name: IX_ShowEvents_Name_City_State; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowEvents_Name_City_State" ON public."ShowEvents" USING btree ("Name", "City", "State");


--
-- Name: IX_ShowFinancialReferences_Edition_Vendor_Kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowFinancialReferences_Edition_Vendor_Kind" ON public."ShowFinancialReferences" USING btree ("ShowEditionId", "ShowVendorProfileId", "Kind");


--
-- Name: IX_ShowForecasts_ShowEditionId_FrozenAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowForecasts_ShowEditionId_FrozenAt" ON public."ShowForecasts" USING btree ("ShowEditionId", "FrozenAt");


--
-- Name: IX_ShowLearnings_ShowEditionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowLearnings_ShowEditionId" ON public."ShowLearnings" USING btree ("ShowEditionId");


--
-- Name: IX_ShowLocations_ShowEventId_Name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowLocations_ShowEventId_Name" ON public."ShowLocations" USING btree ("ShowEventId", "Name");


--
-- Name: IX_ShowMaps_ShowEditionId_Year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowMaps_ShowEditionId_Year" ON public."ShowMaps" USING btree ("ShowEditionId", "Year");


--
-- Name: IX_ShowNotes_ShowEditionId_CreatedAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowNotes_ShowEditionId_CreatedAt" ON public."ShowNotes" USING btree ("ShowEditionId", "CreatedAt");


--
-- Name: IX_ShowNotes_UseForMarketing; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowNotes_UseForMarketing" ON public."ShowNotes" USING btree ("UseForMarketing");


--
-- Name: IX_ShowOpportunities_ShowEditionId_ShowVendorProfileId_Priority; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowOpportunities_ShowEditionId_ShowVendorProfileId_Priority" ON public."ShowOpportunities" USING btree ("ShowEditionId", "ShowVendorProfileId", "Priority");


--
-- Name: IX_ShowResearchEvidence_ShowEditionId_EvidenceType; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowResearchEvidence_ShowEditionId_EvidenceType" ON public."ShowResearchEvidence" USING btree ("ShowEditionId", "EvidenceType");


--
-- Name: IX_ShowResearchGaps_Status_NextCheckAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowResearchGaps_Status_NextCheckAt" ON public."ShowResearchGaps" USING btree ("Status", "NextCheckAt");


--
-- Name: IX_ShowResearchRuns_Edition_StartedAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ShowResearchRuns_Edition_StartedAt" ON public."ShowResearchRuns" USING btree ("ShowEditionId", "StartedAt");


--
-- Name: IX_ShowResults_ShowEditionId_ShowVendorProfileId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowResults_ShowEditionId_ShowVendorProfileId" ON public."ShowResults" USING btree ("ShowEditionId", "ShowVendorProfileId");


--
-- Name: IX_ShowTourStops_ShowTourId_Sequence; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowTourStops_ShowTourId_Sequence" ON public."ShowTourStops" USING btree ("ShowTourId", "Sequence");


--
-- Name: IX_ShowTourStops_ShowTourId_ShowEditionId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowTourStops_ShowTourId_ShowEditionId" ON public."ShowTourStops" USING btree ("ShowTourId", "ShowEditionId");


--
-- Name: IX_ShowVendorCloseouts_Edition_Vendor; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowVendorCloseouts_Edition_Vendor" ON public."ShowVendorCloseouts" USING btree ("ShowEditionId", "ShowVendorProfileId");


--
-- Name: IX_ShowVendorProfiles_ApplicationUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowVendorProfiles_ApplicationUserId" ON public."ShowVendorProfiles" USING btree ("ApplicationUserId") WHERE ("ApplicationUserId" IS NOT NULL);


--
-- Name: IX_ShowVendorProfiles_VendorName; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ShowVendorProfiles_VendorName" ON public."ShowVendorProfiles" USING btree ("VendorName");


--
-- Name: ShowApplications ShowApplications_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowApplications"
    ADD CONSTRAINT "ShowApplications_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowApplications ShowApplications_ShowVendorProfileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowApplications"
    ADD CONSTRAINT "ShowApplications_ShowVendorProfileId_fkey" FOREIGN KEY ("ShowVendorProfileId") REFERENCES public."ShowVendorProfiles"("Id") ON DELETE SET NULL;


--
-- Name: ShowAssignments ShowAssignments_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowAssignments"
    ADD CONSTRAINT "ShowAssignments_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowAssignments ShowAssignments_ShowVendorProfileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowAssignments"
    ADD CONSTRAINT "ShowAssignments_ShowVendorProfileId_fkey" FOREIGN KEY ("ShowVendorProfileId") REFERENCES public."ShowVendorProfiles"("Id") ON DELETE RESTRICT;


--
-- Name: ShowCalibrationRecords ShowCalibrationRecords_ShowEventId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowCalibrationRecords"
    ADD CONSTRAINT "ShowCalibrationRecords_ShowEventId_fkey" FOREIGN KEY ("ShowEventId") REFERENCES public."ShowEvents"("Id") ON DELETE CASCADE;


--
-- Name: ShowDiscoveryLeads ShowDiscoveryLeads_ShowVendorProfileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowDiscoveryLeads"
    ADD CONSTRAINT "ShowDiscoveryLeads_ShowVendorProfileId_fkey" FOREIGN KEY ("ShowVendorProfileId") REFERENCES public."ShowVendorProfiles"("Id") ON DELETE SET NULL;


--
-- Name: ShowEditions ShowEditions_ShowEventId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowEditions"
    ADD CONSTRAINT "ShowEditions_ShowEventId_fkey" FOREIGN KEY ("ShowEventId") REFERENCES public."ShowEvents"("Id") ON DELETE CASCADE;


--
-- Name: ShowForecasts ShowForecasts_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowForecasts"
    ADD CONSTRAINT "ShowForecasts_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowForecasts ShowForecasts_ShowVendorProfileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowForecasts"
    ADD CONSTRAINT "ShowForecasts_ShowVendorProfileId_fkey" FOREIGN KEY ("ShowVendorProfileId") REFERENCES public."ShowVendorProfiles"("Id") ON DELETE SET NULL;


--
-- Name: ShowLearnings ShowLearnings_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowLearnings"
    ADD CONSTRAINT "ShowLearnings_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowLocations ShowLocations_ShowEventId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowLocations"
    ADD CONSTRAINT "ShowLocations_ShowEventId_fkey" FOREIGN KEY ("ShowEventId") REFERENCES public."ShowEvents"("Id") ON DELETE CASCADE;


--
-- Name: ShowMaps ShowMaps_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowMaps"
    ADD CONSTRAINT "ShowMaps_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowNotes ShowNotes_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowNotes"
    ADD CONSTRAINT "ShowNotes_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowNotes ShowNotes_ShowVendorProfileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowNotes"
    ADD CONSTRAINT "ShowNotes_ShowVendorProfileId_fkey" FOREIGN KEY ("ShowVendorProfileId") REFERENCES public."ShowVendorProfiles"("Id") ON DELETE SET NULL;


--
-- Name: ShowOpportunities ShowOpportunities_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowOpportunities"
    ADD CONSTRAINT "ShowOpportunities_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowOpportunities ShowOpportunities_ShowVendorProfileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowOpportunities"
    ADD CONSTRAINT "ShowOpportunities_ShowVendorProfileId_fkey" FOREIGN KEY ("ShowVendorProfileId") REFERENCES public."ShowVendorProfiles"("Id") ON DELETE RESTRICT;


--
-- Name: ShowResearchEvidence ShowResearchEvidence_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResearchEvidence"
    ADD CONSTRAINT "ShowResearchEvidence_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowResearchGaps ShowResearchGaps_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResearchGaps"
    ADD CONSTRAINT "ShowResearchGaps_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowResearchRuns ShowResearchRuns_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResearchRuns"
    ADD CONSTRAINT "ShowResearchRuns_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowResults ShowResults_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResults"
    ADD CONSTRAINT "ShowResults_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowResults ShowResults_ShowVendorProfileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowResults"
    ADD CONSTRAINT "ShowResults_ShowVendorProfileId_fkey" FOREIGN KEY ("ShowVendorProfileId") REFERENCES public."ShowVendorProfiles"("Id") ON DELETE RESTRICT;


--
-- Name: ShowTourStops ShowTourStops_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowTourStops"
    ADD CONSTRAINT "ShowTourStops_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE RESTRICT;


--
-- Name: ShowTourStops ShowTourStops_ShowTourId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowTourStops"
    ADD CONSTRAINT "ShowTourStops_ShowTourId_fkey" FOREIGN KEY ("ShowTourId") REFERENCES public."ShowTours"("Id") ON DELETE CASCADE;


--
-- Name: ShowVendorAssessments ShowVendorAssessments_ShowEditionId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowVendorAssessments"
    ADD CONSTRAINT "ShowVendorAssessments_ShowEditionId_fkey" FOREIGN KEY ("ShowEditionId") REFERENCES public."ShowEditions"("Id") ON DELETE CASCADE;


--
-- Name: ShowVendorAssessments ShowVendorAssessments_ShowVendorProfileId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowVendorAssessments"
    ADD CONSTRAINT "ShowVendorAssessments_ShowVendorProfileId_fkey" FOREIGN KEY ("ShowVendorProfileId") REFERENCES public."ShowVendorProfiles"("Id") ON DELETE CASCADE;


--
-- Name: ShowVendorProfiles ShowVendorProfiles_ApplicationUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShowVendorProfiles"
    ADD CONSTRAINT "ShowVendorProfiles_ApplicationUserId_fkey" FOREIGN KEY ("ApplicationUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--


