<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class AIMS_Schema {
	public function get_table_names(): array {
		global $wpdb;

		return array(
			$wpdb->prefix . 'aims_responsibility_templates',
			$wpdb->prefix . 'aims_template_responsibilities',
			$wpdb->prefix . 'aims_user_responsibilities',
			$wpdb->prefix . 'aims_user_surface_capabilities',
			$wpdb->prefix . 'aims_customers',
			$wpdb->prefix . 'aims_customer_addresses',
			$wpdb->prefix . 'aims_events',
			$wpdb->prefix . 'aims_public_event_catalog',
			$wpdb->prefix . 'aims_public_event_updates',
			$wpdb->prefix . 'aims_event_square_locations',
			$wpdb->prefix . 'aims_event_expenses',
			$wpdb->prefix . 'aims_event_customer_requests',
			$wpdb->prefix . 'aims_event_customer_request_items',
			$wpdb->prefix . 'aims_vendor_event_assignments',
			$wpdb->prefix . 'aims_vendor_event_checkins',
			$wpdb->prefix . 'aims_vendor_event_checkin_media',
			$wpdb->prefix . 'aims_stitch_jobs',
			$wpdb->prefix . 'aims_stitch_job_items',
			$wpdb->prefix . 'aims_stitch_job_item_payout_snapshots',
			$wpdb->prefix . 'aims_storage_locations',
			$wpdb->prefix . 'aims_physical_buckets',
			$wpdb->prefix . 'aims_event_bucket_materials',
			$wpdb->prefix . 'aims_event_bucket_assignments',
			$wpdb->prefix . 'aims_inventory_buckets',
			$wpdb->prefix . 'aims_movement_batches',
			$wpdb->prefix . 'aims_movement_archive_manifests',
			$wpdb->prefix . 'aims_inventory_movements',
			$wpdb->prefix . 'aims_bucket_inventory_positions',
			$wpdb->prefix . 'aims_bucket_inventory_movements',
			$wpdb->prefix . 'aims_inventory_transfers',
			$wpdb->prefix . 'aims_inventory_transfer_items',
			$wpdb->prefix . 'aims_inventory_custody_endpoints',
			$wpdb->prefix . 'aims_inventory_custody_endpoint_relationships',
			$wpdb->prefix . 'aims_sale_fulfillment_allocations',
			$wpdb->prefix . 'aims_product_cost_rules',
			$wpdb->prefix . 'aims_sync_runs',
			$wpdb->prefix . 'aims_sync_actions',
			$wpdb->prefix . 'aims_sync_effects',
			$wpdb->prefix . 'aims_square_import_queue',
			$wpdb->prefix . 'aims_square_raw_events',
			$wpdb->prefix . 'aims_square_team_members',
			$wpdb->prefix . 'aims_runtime_assignments',
			$wpdb->prefix . 'aims_square_normalized_sales',
			$wpdb->prefix . 'aims_sales_exceptions',
			$wpdb->prefix . 'aims_vendor_sales_attribution',
			$wpdb->prefix . 'aims_square_sales',
			$wpdb->prefix . 'aims_event_reconciliations',
			$wpdb->prefix . 'aims_event_reconciliation_discrepancies',
		);
	}

	public function get_table_definitions(): array {
		global $wpdb;

		$charset_collate         = $wpdb->get_charset_collate();
		$responsibility_templates_table = $wpdb->prefix . 'aims_responsibility_templates';
		$template_responsibilities_table = $wpdb->prefix . 'aims_template_responsibilities';
		$user_responsibilities_table = $wpdb->prefix . 'aims_user_responsibilities';
		$user_surface_capabilities_table = $wpdb->prefix . 'aims_user_surface_capabilities';
		$customers_table         = $wpdb->prefix . 'aims_customers';
		$customer_addresses_table = $wpdb->prefix . 'aims_customer_addresses';
		$events_table            = $wpdb->prefix . 'aims_events';
		$public_event_catalog_table = $wpdb->prefix . 'aims_public_event_catalog';
		$public_event_updates_table = $wpdb->prefix . 'aims_public_event_updates';
		$event_square_locations_table = $wpdb->prefix . 'aims_event_square_locations';
		$event_expenses_table    = $wpdb->prefix . 'aims_event_expenses';
		$event_customer_requests_table = $wpdb->prefix . 'aims_event_customer_requests';
		$event_customer_request_items_table = $wpdb->prefix . 'aims_event_customer_request_items';
		$event_assignments_table = $wpdb->prefix . 'aims_vendor_event_assignments';
		$vendor_event_checkins_table = $wpdb->prefix . 'aims_vendor_event_checkins';
		$vendor_event_checkin_media_table = $wpdb->prefix . 'aims_vendor_event_checkin_media';
		$stitch_jobs_table       = $wpdb->prefix . 'aims_stitch_jobs';
		$stitch_job_items_table  = $wpdb->prefix . 'aims_stitch_job_items';
		$stitch_job_item_payout_snapshots_table = $wpdb->prefix . 'aims_stitch_job_item_payout_snapshots';
		$storage_locations_table = $wpdb->prefix . 'aims_storage_locations';
		$physical_buckets_table  = $wpdb->prefix . 'aims_physical_buckets';
		$event_bucket_materials_table = $wpdb->prefix . 'aims_event_bucket_materials';
		$event_bucket_assignments_table = $wpdb->prefix . 'aims_event_bucket_assignments';
		$inventory_buckets_table = $wpdb->prefix . 'aims_inventory_buckets';
		$movement_batches_table  = $wpdb->prefix . 'aims_movement_batches';
		$movement_archive_manifests_table = $wpdb->prefix . 'aims_movement_archive_manifests';
		$inventory_moves_table   = $wpdb->prefix . 'aims_inventory_movements';
		$bucket_positions_table  = $wpdb->prefix . 'aims_bucket_inventory_positions';
		$bucket_moves_table      = $wpdb->prefix . 'aims_bucket_inventory_movements';
		$inventory_transfers_table = $wpdb->prefix . 'aims_inventory_transfers';
		$inventory_transfer_items_table = $wpdb->prefix . 'aims_inventory_transfer_items';
		$inventory_custody_endpoints_table = $wpdb->prefix . 'aims_inventory_custody_endpoints';
		$inventory_custody_endpoint_relationships_table = $wpdb->prefix . 'aims_inventory_custody_endpoint_relationships';
		$fulfillment_allocations_table = $wpdb->prefix . 'aims_sale_fulfillment_allocations';
		$product_cost_rules_table = $wpdb->prefix . 'aims_product_cost_rules';
		$sync_runs_table         = $wpdb->prefix . 'aims_sync_runs';
		$sync_actions_table      = $wpdb->prefix . 'aims_sync_actions';
		$sync_effects_table      = $wpdb->prefix . 'aims_sync_effects';
		$square_queue_table      = $wpdb->prefix . 'aims_square_import_queue';
		$square_raw_events_table = $wpdb->prefix . 'aims_square_raw_events';
		$square_team_members_table = $wpdb->prefix . 'aims_square_team_members';
		$runtime_assignments_table = $wpdb->prefix . 'aims_runtime_assignments';
		$square_normalized_sales_table = $wpdb->prefix . 'aims_square_normalized_sales';
		$sales_exceptions_table  = $wpdb->prefix . 'aims_sales_exceptions';
		$vendor_sales_attribution_table = $wpdb->prefix . 'aims_vendor_sales_attribution';
		$square_sales_table      = $wpdb->prefix . 'aims_square_sales';
		$event_reconciliations_table = $wpdb->prefix . 'aims_event_reconciliations';
		$event_reconciliation_discrepancies_table = $wpdb->prefix . 'aims_event_reconciliation_discrepancies';

		return array(
			"CREATE TABLE {$responsibility_templates_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				template_key varchar(100) NOT NULL,
				template_name varchar(190) NOT NULL,
				template_status varchar(32) NOT NULL DEFAULT 'active',
				description longtext NULL,
				is_system tinyint(1) NOT NULL DEFAULT 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY template_key (template_key),
				KEY template_status (template_status),
				KEY is_system (is_system)
			) {$charset_collate};",
			"CREATE TABLE {$template_responsibilities_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				template_key varchar(100) NOT NULL,
				responsibility_key varchar(100) NOT NULL,
				scope_type varchar(32) NOT NULL DEFAULT 'global',
				scope_ref_id bigint(20) unsigned NOT NULL DEFAULT 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY template_responsibility_scope (template_key, responsibility_key, scope_type, scope_ref_id),
				KEY template_key (template_key),
				KEY responsibility_key (responsibility_key),
				KEY scope_lookup (scope_type, scope_ref_id)
			) {$charset_collate};",
			"CREATE TABLE {$user_responsibilities_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				user_id bigint(20) unsigned NOT NULL,
				responsibility_key varchar(100) NOT NULL,
				scope_type varchar(32) NOT NULL DEFAULT 'global',
				scope_ref_id bigint(20) unsigned NOT NULL DEFAULT 0,
				template_key varchar(100) NOT NULL DEFAULT '',
				override_mode varchar(16) NOT NULL DEFAULT 'allow',
				is_active tinyint(1) NOT NULL DEFAULT 1,
				granted_by bigint(20) unsigned DEFAULT NULL,
				granted_at datetime NULL DEFAULT NULL,
				revoked_by bigint(20) unsigned DEFAULT NULL,
				revoked_at datetime NULL DEFAULT NULL,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY user_active_lookup (user_id, is_active),
				KEY responsibility_lookup (responsibility_key, is_active),
				KEY scope_lookup (scope_type, scope_ref_id, is_active),
				KEY template_key (template_key),
				KEY granted_by (granted_by),
				KEY revoked_by (revoked_by)
			) {$charset_collate};",
			"CREATE TABLE {$user_surface_capabilities_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				user_id bigint(20) unsigned NOT NULL,
				capability_key varchar(100) NOT NULL,
				surface varchar(32) NOT NULL DEFAULT 'wp_admin',
				scope_type varchar(32) NOT NULL DEFAULT 'global',
				scope_ref_id bigint(20) unsigned NOT NULL DEFAULT 0,
				access_mode varchar(16) NOT NULL DEFAULT 'deny',
				is_active tinyint(1) NOT NULL DEFAULT 1,
				note text NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY user_capability_surface_scope (user_id, capability_key, surface, scope_type, scope_ref_id),
				KEY user_id (user_id),
				KEY capability_key (capability_key),
				KEY surface (surface),
				KEY scope_lookup (scope_type, scope_ref_id),
				KEY access_mode (access_mode),
				KEY is_active (is_active)
			) {$charset_collate};",
			"CREATE TABLE {$customers_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				square_customer_id varchar(191) NOT NULL DEFAULT '',
				first_name varchar(100) NOT NULL DEFAULT '',
				last_name varchar(100) NOT NULL DEFAULT '',
				company_name varchar(255) NOT NULL DEFAULT '',
				email_address varchar(190) NOT NULL DEFAULT '',
				phone_number varchar(50) NOT NULL DEFAULT '',
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY square_customer_id (square_customer_id),
				KEY email_address (email_address),
				KEY phone_number (phone_number)
			) {$charset_collate};",
			"CREATE TABLE {$customer_addresses_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				customer_id bigint(20) unsigned NOT NULL,
				square_address_id varchar(191) NOT NULL DEFAULT '',
				address_type varchar(20) NOT NULL DEFAULT 'shipping',
				is_primary tinyint(1) NOT NULL DEFAULT 0,
				address_line_1 varchar(255) NOT NULL DEFAULT '',
				address_line_2 varchar(255) NOT NULL DEFAULT '',
				city varchar(100) NOT NULL DEFAULT '',
				state_region varchar(100) NOT NULL DEFAULT '',
				postal_code varchar(30) NOT NULL DEFAULT '',
				country_code varchar(2) NOT NULL DEFAULT 'US',
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY square_address_id (square_address_id),
				KEY customer_id (customer_id),
				KEY address_type (address_type),
				KEY is_primary (is_primary)
			) {$charset_collate};",
			"CREATE TABLE {$events_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_code varchar(64) NOT NULL DEFAULT '',
				event_name varchar(255) NOT NULL,
				status varchar(32) NOT NULL DEFAULT 'draft',
				start_date date NOT NULL,
				end_date date NOT NULL,
				location_name varchar(191) NOT NULL DEFAULT '',
				square_location_id varchar(191) NOT NULL DEFAULT '',
				source varchar(50) NOT NULL DEFAULT 'aims',
				gross_sales_total decimal(20,2) NOT NULL DEFAULT 0.00,
				discount_total decimal(20,2) NOT NULL DEFAULT 0.00,
				tip_total decimal(20,2) NOT NULL DEFAULT 0.00,
				net_sales_total decimal(20,2) NOT NULL DEFAULT 0.00,
				vendor_payout_total decimal(20,2) NOT NULL DEFAULT 0.00,
				expense_total decimal(20,2) NOT NULL DEFAULT 0.00,
				profit_total decimal(20,2) NOT NULL DEFAULT 0.00,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY event_code (event_code),
				KEY status (status),
				KEY start_date (start_date),
				KEY end_date (end_date),
				KEY square_location_id (square_location_id)
			) {$charset_collate};",
			"CREATE TABLE {$public_event_catalog_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				slug varchar(191) NOT NULL DEFAULT '',
				public_title varchar(255) NOT NULL DEFAULT '',
				public_summary longtext NULL,
				venue_name varchar(191) NOT NULL DEFAULT '',
				city varchar(100) NOT NULL DEFAULT '',
				state_region varchar(100) NOT NULL DEFAULT '',
				start_date date NOT NULL,
				end_date date NOT NULL,
				public_status varchar(32) NOT NULL DEFAULT 'draft',
				hero_image_reference varchar(191) NOT NULL DEFAULT '',
				is_featured tinyint(1) NOT NULL DEFAULT 0,
				sort_date datetime NULL DEFAULT NULL,
				request_intake_enabled tinyint(1) NOT NULL DEFAULT 0,
				last_projected_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY event_id (event_id),
				UNIQUE KEY slug (slug),
				KEY public_status (public_status),
				KEY start_date (start_date),
				KEY end_date (end_date),
				KEY is_featured (is_featured),
				KEY sort_date (sort_date),
				KEY request_intake_enabled (request_intake_enabled),
				KEY last_projected_at (last_projected_at)
			) {$charset_collate};",
			"CREATE TABLE {$public_event_updates_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				update_slug varchar(191) NOT NULL DEFAULT '',
				update_type varchar(50) NOT NULL DEFAULT 'update',
				update_title varchar(255) NOT NULL DEFAULT '',
				update_summary longtext NULL,
				update_body longtext NULL,
				public_status varchar(32) NOT NULL DEFAULT 'published',
				is_pinned tinyint(1) NOT NULL DEFAULT 0,
				hero_image_reference varchar(191) NOT NULL DEFAULT '',
				source_label varchar(191) NOT NULL DEFAULT '',
				source_reference varchar(191) NOT NULL DEFAULT '',
				published_at datetime NULL DEFAULT NULL,
				last_projected_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY event_update_slug (event_id, update_slug),
				KEY event_id (event_id),
				KEY update_slug (update_slug),
				KEY update_type (update_type),
				KEY public_status (public_status),
				KEY is_pinned (is_pinned),
				KEY published_at (published_at),
				KEY last_projected_at (last_projected_at)
			) {$charset_collate};",
			"CREATE TABLE {$event_square_locations_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				square_location_id varchar(191) NOT NULL DEFAULT '',
				is_primary tinyint(1) NOT NULL DEFAULT 0,
				active_from datetime NULL DEFAULT NULL,
				active_to datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY event_location (event_id, square_location_id),
				KEY square_location_id (square_location_id),
				KEY is_primary (is_primary),
				KEY active_from (active_from),
				KEY active_to (active_to)
			) {$charset_collate};",
			"CREATE TABLE {$event_expenses_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				expense_type varchar(50) NOT NULL DEFAULT 'other',
				amount decimal(20,2) NOT NULL DEFAULT 0.00,
				note text NULL,
				incurred_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY event_id (event_id),
				KEY vendor_id (vendor_id),
				KEY expense_type (expense_type),
				KEY incurred_at (incurred_at)
			) {$charset_collate};",
			"CREATE TABLE {$event_customer_requests_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				wp_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				customer_id bigint(20) unsigned NOT NULL DEFAULT 0,
				customer_name varchar(191) NOT NULL DEFAULT '',
				customer_email varchar(190) NOT NULL DEFAULT '',
				customer_phone varchar(50) NOT NULL DEFAULT '',
				status varchar(32) NOT NULL DEFAULT 'planned',
				request_source varchar(50) NOT NULL DEFAULT 'event_customer_request',
				request_status varchar(32) NOT NULL DEFAULT 'approved',
				approval_mode varchar(50) NOT NULL DEFAULT 'auto_planning_signal',
				notes longtext NULL,
				submitted_at datetime NULL DEFAULT NULL,
				requested_at datetime NULL DEFAULT NULL,
				approved_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY event_id (event_id),
				KEY status (status),
				KEY wp_user_id (wp_user_id),
				KEY vendor_id (vendor_id),
				KEY customer_id (customer_id),
				KEY request_status (request_status),
				KEY submitted_at (submitted_at),
				KEY requested_at (requested_at)
			) {$charset_collate};",
			"CREATE TABLE {$event_customer_request_items_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				request_id bigint(20) unsigned NOT NULL,
				event_id bigint(20) unsigned NOT NULL,
				woo_product_id bigint(20) unsigned NOT NULL,
				product_sku varchar(191) NOT NULL DEFAULT '',
				product_name varchar(191) NOT NULL DEFAULT '',
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				quantity_requested decimal(20,4) NOT NULL DEFAULT 0.0000,
				notes longtext NULL,
				request_note text NULL,
				item_status varchar(32) NOT NULL DEFAULT 'planned',
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY request_id (request_id),
				KEY event_id (event_id),
				KEY item_status (item_status),
				KEY woo_product_id (woo_product_id),
				KEY product_sku (product_sku),
				KEY vendor_id (vendor_id)
			) {$charset_collate};",
			"CREATE TABLE {$event_assignments_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				vendor_id bigint(20) unsigned NOT NULL,
				assignment_status varchar(32) NOT NULL DEFAULT 'assigned',
				commission_rate decimal(7,4) NOT NULL DEFAULT 0.0000,
				fulfillment_status varchar(32) NOT NULL DEFAULT 'pending',
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY event_vendor (event_id, vendor_id),
				KEY vendor_id (vendor_id),
				KEY assignment_status (assignment_status),
				KEY fulfillment_status (fulfillment_status)
			) {$charset_collate};",
			"CREATE TABLE {$vendor_event_checkins_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				vendor_id bigint(20) unsigned NOT NULL,
				vendor_event_assignment_id bigint(20) unsigned NOT NULL DEFAULT 0,
				physical_bucket_id bigint(20) unsigned NOT NULL DEFAULT 0,
				public_event_update_id bigint(20) unsigned NOT NULL DEFAULT 0,
				checkin_source varchar(50) NOT NULL DEFAULT 'vendor_portal',
				checkin_status varchar(32) NOT NULL DEFAULT 'recorded',
				visibility_status varchar(32) NOT NULL DEFAULT 'internal',
				is_first_checkin tinyint(1) NOT NULL DEFAULT 1,
				movement_applied tinyint(1) NOT NULL DEFAULT 0,
				movement_applied_at datetime NULL DEFAULT NULL,
				movement_reference_type varchar(50) NOT NULL DEFAULT '',
				movement_reference_id varchar(191) NOT NULL DEFAULT '',
				checkin_notes longtext NULL,
				checkin_comment longtext NULL,
				mobile_photo_reference varchar(191) NOT NULL DEFAULT '',
				checked_in_by bigint(20) unsigned NOT NULL DEFAULT 0,
				checked_in_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY event_vendor_bucket (event_id, vendor_id, physical_bucket_id),
				KEY event_id (event_id),
				KEY vendor_id (vendor_id),
				KEY vendor_event_assignment_id (vendor_event_assignment_id),
				KEY physical_bucket_id (physical_bucket_id),
				KEY public_event_update_id (public_event_update_id),
				KEY checkin_source (checkin_source),
				KEY checkin_status (checkin_status),
				KEY visibility_status (visibility_status),
				KEY is_first_checkin (is_first_checkin),
				KEY movement_applied (movement_applied),
				KEY movement_reference_type (movement_reference_type),
				KEY movement_reference_id (movement_reference_id),
				KEY checked_in_at (checked_in_at)
			) {$charset_collate};",
			"CREATE TABLE {$vendor_event_checkin_media_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				checkin_id bigint(20) unsigned NOT NULL DEFAULT 0,
				public_event_update_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				media_type varchar(32) NOT NULL DEFAULT 'photo',
				media_source varchar(50) NOT NULL DEFAULT 'mobile_upload',
				media_reference varchar(191) NOT NULL DEFAULT '',
				media_url varchar(255) NOT NULL DEFAULT '',
				attachment_id bigint(20) unsigned NOT NULL DEFAULT 0,
				caption longtext NULL,
				alt_text varchar(191) NOT NULL DEFAULT '',
				visibility_status varchar(32) NOT NULL DEFAULT 'internal',
				is_primary tinyint(1) NOT NULL DEFAULT 0,
				sort_order int(11) NOT NULL DEFAULT 0,
				uploaded_by bigint(20) unsigned NOT NULL DEFAULT 0,
				uploaded_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY checkin_id (checkin_id),
				KEY public_event_update_id (public_event_update_id),
				KEY event_id (event_id),
				KEY vendor_id (vendor_id),
				KEY media_type (media_type),
				KEY media_source (media_source),
				KEY media_reference (media_reference),
				KEY visibility_status (visibility_status),
				KEY is_primary (is_primary),
				KEY sort_order (sort_order)
			) {$charset_collate};",
			"CREATE TABLE {$stitch_jobs_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				job_code varchar(64) NOT NULL DEFAULT '',
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				assigned_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
				producer_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
				status varchar(32) NOT NULL DEFAULT 'queued',
				priority varchar(20) NOT NULL DEFAULT 'normal',
				due_at datetime NULL DEFAULT NULL,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY job_code (job_code),
				KEY vendor_id (vendor_id),
				KEY event_id (event_id),
				KEY assigned_user_id (assigned_user_id),
				KEY producer_user_id (producer_user_id),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$stitch_job_items_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				stitch_job_id bigint(20) unsigned NOT NULL DEFAULT 0,
				line_number int(11) unsigned NOT NULL DEFAULT 1,
				product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				producer_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
				stitcher_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
				stitch_job_type varchar(50) NOT NULL DEFAULT '',
				status varchar(32) NOT NULL DEFAULT 'queued',
				quantity_requested decimal(20,4) NOT NULL DEFAULT 0.0000,
				quantity_completed decimal(20,4) NOT NULL DEFAULT 0.0000,
				quantity_received_back decimal(20,4) NOT NULL DEFAULT 0.0000,
				unit_payout_snapshot decimal(20,4) NOT NULL DEFAULT 0.0000,
				payout_snapshot_source varchar(50) NOT NULL DEFAULT '',
				payout_snapshot_rule_id bigint(20) unsigned NOT NULL DEFAULT 0,
				snapshot_taken_at datetime NULL DEFAULT NULL,
				labels_prepared_at datetime NULL DEFAULT NULL,
				labels_prepared_by bigint(20) unsigned NOT NULL DEFAULT 0,
				labels_prepared_quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				label_template_key varchar(100) NOT NULL DEFAULT '',
				assigned_at datetime NULL DEFAULT NULL,
				completed_at datetime NULL DEFAULT NULL,
				received_back_at datetime NULL DEFAULT NULL,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY stitch_job_line (stitch_job_id, line_number),
				KEY stitch_job_id (stitch_job_id),
				KEY product_id (product_id),
				KEY vendor_id (vendor_id),
				KEY producer_user_id (producer_user_id),
				KEY stitcher_user_id (stitcher_user_id),
				KEY labels_prepared_by (labels_prepared_by),
				KEY label_template_key (label_template_key),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$stitch_job_item_payout_snapshots_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				stitch_job_item_id bigint(20) unsigned NOT NULL DEFAULT 0,
				stitch_job_id bigint(20) unsigned NOT NULL DEFAULT 0,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				producer_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
				stitcher_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
				product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				assignment_type varchar(32) NOT NULL DEFAULT 'product',
				stitch_job_type varchar(50) NOT NULL DEFAULT '',
				snapshot_source varchar(50) NOT NULL DEFAULT 'default_fallback',
				snapshot_priority int(11) unsigned NOT NULL DEFAULT 0,
				snapshot_rule_id bigint(20) unsigned NOT NULL DEFAULT 0,
				unit_payout_snapshot decimal(20,4) NOT NULL DEFAULT 0.0000,
				snapshot_quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				captured_at datetime NOT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY stitch_job_item_id (stitch_job_item_id),
				KEY stitch_job_id (stitch_job_id),
				KEY vendor_id (vendor_id),
				KEY producer_user_id (producer_user_id),
				KEY stitcher_user_id (stitcher_user_id),
				KEY product_id (product_id),
				KEY snapshot_source (snapshot_source)
			) {$charset_collate};",
			"CREATE TABLE {$storage_locations_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				location_code varchar(64) NOT NULL DEFAULT '',
				location_name varchar(191) NOT NULL DEFAULT '',
				location_type varchar(32) NOT NULL DEFAULT 'bin',
				parent_location_id bigint(20) unsigned NOT NULL DEFAULT 0,
				sort_order int(11) NOT NULL DEFAULT 0,
				is_pickable tinyint(1) NOT NULL DEFAULT 0,
				is_staging tinyint(1) NOT NULL DEFAULT 0,
				status varchar(32) NOT NULL DEFAULT 'active',
				barcode_value varchar(191) NOT NULL DEFAULT '',
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY location_code (location_code),
				KEY parent_location_id (parent_location_id),
				KEY location_type (location_type),
				KEY status (status),
				KEY is_pickable (is_pickable),
				KEY is_staging (is_staging),
				KEY barcode_value (barcode_value)
			) {$charset_collate};",
			"CREATE TABLE {$physical_buckets_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				bucket_code varchar(64) NOT NULL DEFAULT '',
				bucket_label varchar(191) NOT NULL DEFAULT '',
				bucket_type varchar(32) NOT NULL DEFAULT 'warehouse_stock',
				status varchar(32) NOT NULL DEFAULT 'available',
				is_sealed tinyint(1) NOT NULL DEFAULT 0,
				square_location_id varchar(191) NOT NULL DEFAULT '',
				current_storage_location_id bigint(20) unsigned NOT NULL DEFAULT 0,
				home_storage_location_id bigint(20) unsigned NOT NULL DEFAULT 0,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				barcode_value varchar(191) NOT NULL DEFAULT '',
				tare_weight decimal(12,4) NOT NULL DEFAULT 0.0000,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY bucket_code (bucket_code),
				KEY status (status),
				KEY is_sealed (is_sealed),
				KEY square_location_id (square_location_id),
				KEY bucket_type (bucket_type),
				KEY current_storage_location_id (current_storage_location_id),
				KEY home_storage_location_id (home_storage_location_id),
				KEY vendor_id (vendor_id),
				KEY barcode_value (barcode_value)
			) {$charset_collate};",
			"CREATE TABLE {$event_bucket_materials_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				physical_bucket_id bigint(20) unsigned NOT NULL,
				material_key varchar(100) NOT NULL DEFAULT '',
				label varchar(191) NOT NULL DEFAULT '',
				quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				unit varchar(32) NOT NULL DEFAULT '',
				is_required tinyint(1) NOT NULL DEFAULT 0,
				is_consumable tinyint(1) NOT NULL DEFAULT 1,
				packed_status varchar(32) NOT NULL DEFAULT 'planned',
				notes text NULL,
				sort_order int(11) NOT NULL DEFAULT 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY event_bucket_material (event_id, physical_bucket_id, material_key),
				KEY event_id (event_id),
				KEY physical_bucket_id (physical_bucket_id),
				KEY packed_status (packed_status),
				KEY is_required (is_required),
				KEY sort_order (sort_order)
			) {$charset_collate};",
			"CREATE TABLE {$event_bucket_assignments_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				physical_bucket_id bigint(20) unsigned NOT NULL,
				assignment_status varchar(32) NOT NULL DEFAULT 'assigned',
				assignment_type varchar(32) NOT NULL DEFAULT 'event_stock',
				assigned_at datetime NULL DEFAULT NULL,
				loaded_at datetime NULL DEFAULT NULL,
				in_transit_at datetime NULL DEFAULT NULL,
				released_at datetime NULL DEFAULT NULL,
				assigned_by bigint(20) unsigned NOT NULL DEFAULT 0,
				released_by bigint(20) unsigned NOT NULL DEFAULT 0,
				display_order int(11) NOT NULL DEFAULT 0,
				is_active tinyint(1) NOT NULL DEFAULT 1,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY event_id (event_id),
				KEY physical_bucket_id (physical_bucket_id),
				KEY event_bucket_active_lookup (event_id, is_active, display_order),
				KEY bucket_active_lookup (physical_bucket_id, is_active),
				KEY event_bucket_history_lookup (event_id, physical_bucket_id, assigned_at),
				KEY assignment_status (assignment_status),
				KEY assignment_type (assignment_type),
				KEY is_active (is_active),
				KEY assigned_at (assigned_at),
				KEY loaded_at (loaded_at),
				KEY in_transit_at (in_transit_at),
				KEY released_at (released_at)
			) {$charset_collate};",
			"CREATE TABLE {$inventory_buckets_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				bucket_id bigint(20) unsigned DEFAULT NULL,
				bucket_code varchar(191) NOT NULL DEFAULT '',
				bucket_name varchar(191) NOT NULL DEFAULT '',
				quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				reserved_quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY vendor_product_bucket (vendor_id, product_id, bucket_code),
				KEY vendor_id (vendor_id),
				KEY product_id (product_id),
				KEY bucket_id (bucket_id),
				KEY bucket_code (bucket_code)
			) {$charset_collate};",
			"CREATE TABLE {$movement_batches_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				batch_uuid varchar(36) NOT NULL DEFAULT '',
				batch_type varchar(50) NOT NULL DEFAULT 'bucket_line_meta',
				reference_type varchar(50) NOT NULL DEFAULT '',
				reference_id varchar(191) NOT NULL DEFAULT '',
				movement_type varchar(50) NOT NULL DEFAULT '',
				lifecycle_status varchar(32) NOT NULL DEFAULT 'hot',
				line_count int(11) unsigned NOT NULL DEFAULT 0,
				total_quantity_delta decimal(20,4) NOT NULL DEFAULT 0.0000,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				stitch_job_id bigint(20) unsigned NOT NULL DEFAULT 0,
				bucket_id bigint(20) unsigned NOT NULL DEFAULT 0,
				created_by bigint(20) unsigned NOT NULL DEFAULT 0,
				last_line_at datetime NULL DEFAULT NULL,
				archive_manifest_id bigint(20) unsigned NOT NULL DEFAULT 0,
				archive_compression varchar(32) NOT NULL DEFAULT 'none',
				batch_summary_json longtext NULL,
				line_meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY batch_uuid (batch_uuid),
				UNIQUE KEY reference_batch (reference_type, reference_id, movement_type, batch_type),
				KEY lifecycle_status (lifecycle_status),
				KEY vendor_id (vendor_id),
				KEY event_id (event_id),
				KEY stitch_job_id (stitch_job_id),
				KEY bucket_id (bucket_id),
				KEY archive_manifest_id (archive_manifest_id),
				KEY last_line_at (last_line_at)
			) {$charset_collate};",
			"CREATE TABLE {$movement_archive_manifests_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				archive_key varchar(191) NOT NULL DEFAULT '',
				movement_batch_id bigint(20) unsigned NOT NULL DEFAULT 0,
				archive_status varchar(32) NOT NULL DEFAULT 'prepared',
				storage_backend varchar(32) NOT NULL DEFAULT 'local_wp',
				archive_format varchar(32) NOT NULL DEFAULT 'json',
				compression_codec varchar(32) NOT NULL DEFAULT 'gzip',
				storage_path varchar(255) NOT NULL DEFAULT '',
				payload_checksum varchar(191) NOT NULL DEFAULT '',
				line_count int(11) unsigned NOT NULL DEFAULT 0,
				payload_bytes bigint(20) unsigned NOT NULL DEFAULT 0,
				manifest_json longtext NULL,
				payload_json longtext NULL,
				exported_at datetime NULL DEFAULT NULL,
				archived_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY archive_key (archive_key),
				UNIQUE KEY movement_batch_id (movement_batch_id),
				KEY archive_status (archive_status),
				KEY compression_codec (compression_codec),
				KEY exported_at (exported_at),
				KEY archived_at (archived_at)
			) {$charset_collate};",
			"CREATE TABLE {$inventory_moves_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				movement_uuid varchar(36) NOT NULL DEFAULT '',
				movement_batch_id bigint(20) unsigned NOT NULL DEFAULT 0,
				reference_type varchar(50) NOT NULL DEFAULT '',
				reference_id varchar(191) NOT NULL DEFAULT '',
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				stitch_job_id bigint(20) unsigned NOT NULL DEFAULT 0,
				product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				bucket_id bigint(20) unsigned DEFAULT NULL,
				bucket_code varchar(191) NOT NULL DEFAULT '',
				movement_type varchar(50) NOT NULL DEFAULT '',
				quantity_delta decimal(20,4) NOT NULL DEFAULT 0.0000,
				movement_lifecycle varchar(32) NOT NULL DEFAULT 'hot',
				archive_manifest_id bigint(20) unsigned NOT NULL DEFAULT 0,
				applied_by bigint(20) unsigned NOT NULL DEFAULT 0,
				note text NULL,
				line_meta_json longtext NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY movement_uuid (movement_uuid),
				UNIQUE KEY apply_once_ref (reference_type, reference_id, product_id, bucket_code, movement_type),
				KEY movement_batch_id (movement_batch_id),
				KEY movement_lifecycle (movement_lifecycle),
				KEY archive_manifest_id (archive_manifest_id),
				KEY vendor_id (vendor_id),
				KEY event_id (event_id),
				KEY stitch_job_id (stitch_job_id),
				KEY product_id (product_id),
				KEY bucket_id (bucket_id),
				KEY bucket_code (bucket_code),
				KEY movement_type (movement_type)
			) {$charset_collate};",
			"CREATE TABLE {$bucket_positions_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				bucket_id bigint(20) unsigned NOT NULL,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				reserved_quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				position_status varchar(32) NOT NULL DEFAULT 'active',
				last_bucket_movement_id bigint(20) unsigned NOT NULL DEFAULT 0,
				last_counted_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY bucket_vendor_product (bucket_id, vendor_id, product_id),
				KEY vendor_id (vendor_id),
				KEY product_id (product_id),
				KEY position_status (position_status),
				KEY last_bucket_movement_id (last_bucket_movement_id)
			) {$charset_collate};",
			"CREATE TABLE {$bucket_moves_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				movement_uuid varchar(36) NOT NULL DEFAULT '',
				movement_batch_id bigint(20) unsigned NOT NULL DEFAULT 0,
				reference_type varchar(50) NOT NULL DEFAULT '',
				reference_id varchar(191) NOT NULL DEFAULT '',
				bucket_id bigint(20) unsigned NOT NULL,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				fulfillment_allocation_id bigint(20) unsigned NOT NULL DEFAULT 0,
				source_bucket_id bigint(20) unsigned NOT NULL DEFAULT 0,
				target_bucket_id bigint(20) unsigned NOT NULL DEFAULT 0,
				source_storage_location_id bigint(20) unsigned NOT NULL DEFAULT 0,
				target_storage_location_id bigint(20) unsigned NOT NULL DEFAULT 0,
				square_location_id varchar(191) NOT NULL DEFAULT '',
				movement_type varchar(50) NOT NULL DEFAULT '',
				quantity_delta decimal(20,4) NOT NULL DEFAULT 0.0000,
				sealed_state tinyint(1) NOT NULL DEFAULT 0,
				movement_lifecycle varchar(32) NOT NULL DEFAULT 'hot',
				archive_manifest_id bigint(20) unsigned NOT NULL DEFAULT 0,
				applied_by bigint(20) unsigned NOT NULL DEFAULT 0,
				note text NULL,
				metadata_json longtext NULL,
				line_meta_json longtext NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY movement_uuid (movement_uuid),
				UNIQUE KEY apply_once_ref (reference_type, reference_id, product_id, bucket_id, movement_type),
				KEY movement_batch_id (movement_batch_id),
				KEY movement_lifecycle (movement_lifecycle),
				KEY sealed_state (sealed_state),
				KEY archive_manifest_id (archive_manifest_id),
				KEY bucket_id (bucket_id),
				KEY vendor_id (vendor_id),
				KEY event_id (event_id),
				KEY square_location_id (square_location_id),
				KEY product_id (product_id),
				KEY fulfillment_allocation_id (fulfillment_allocation_id),
				KEY source_bucket_id (source_bucket_id),
				KEY target_bucket_id (target_bucket_id),
				KEY source_storage_location_id (source_storage_location_id),
				KEY target_storage_location_id (target_storage_location_id),
				KEY movement_type (movement_type)
			) {$charset_collate};",
			"CREATE TABLE {$inventory_transfers_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				transfer_uuid varchar(36) NOT NULL DEFAULT '',
				transfer_code varchar(64) NOT NULL DEFAULT '',
				source_node_type varchar(32) NOT NULL DEFAULT 'vendor',
				source_node_id bigint(20) unsigned NOT NULL DEFAULT 0,
				target_node_type varchar(32) NOT NULL DEFAULT 'vendor',
				target_node_id bigint(20) unsigned NOT NULL DEFAULT 0,
				source_vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				target_vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				transfer_status varchar(32) NOT NULL DEFAULT 'pending',
				transfer_type varchar(32) NOT NULL DEFAULT 'standard',
				dispatch_requested_at datetime NULL,
				dispatch_confirmed_at datetime NULL DEFAULT NULL,
				receipt_expected_at datetime NULL DEFAULT NULL,
				receipt_confirmed_at datetime NULL DEFAULT NULL,
				cancelled_at datetime NULL DEFAULT NULL,
				initiated_by bigint(20) unsigned NOT NULL DEFAULT 0,
				received_by bigint(20) unsigned NOT NULL DEFAULT 0,
				cancelled_by bigint(20) unsigned NOT NULL DEFAULT 0,
				reference_type varchar(50) NOT NULL DEFAULT '',
				reference_id varchar(191) NOT NULL DEFAULT '',
				override_route varchar(64) NOT NULL DEFAULT '',
				override_reason varchar(191) NOT NULL DEFAULT '',
				override_note longtext NULL,
				override_actor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				override_at datetime NULL DEFAULT NULL,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY transfer_code (transfer_code),
				UNIQUE KEY transfer_uuid (transfer_uuid),
				KEY transfer_status (transfer_status),
				KEY transfer_type (transfer_type),
				KEY source_node_type (source_node_type),
				KEY source_node_id (source_node_id),
				KEY target_node_type (target_node_type),
				KEY target_node_id (target_node_id),
				KEY source_vendor_id (source_vendor_id),
				KEY target_vendor_id (target_vendor_id),
				KEY reference_type (reference_type),
				KEY reference_id (reference_id),
				KEY dispatch_confirmed_at (dispatch_confirmed_at),
				KEY receipt_confirmed_at (receipt_confirmed_at),
				KEY override_route (override_route),
				KEY override_actor_id (override_actor_id),
				KEY initiated_by (initiated_by),
				KEY received_by (received_by)
			) {$charset_collate};",
			"CREATE TABLE {$inventory_transfer_items_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				transfer_id bigint(20) unsigned NOT NULL,
				transfer_uuid varchar(36) NOT NULL DEFAULT '',
				line_number int(11) unsigned NOT NULL DEFAULT 1,
				product_id bigint(20) unsigned NOT NULL,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				requested_quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				dispatched_quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				received_quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				variance_quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				line_status varchar(32) NOT NULL DEFAULT 'pending',
				source_bucket_id bigint(20) unsigned NOT NULL DEFAULT 0,
				target_bucket_id bigint(20) unsigned NOT NULL DEFAULT 0,
				source_bucket_code varchar(191) NOT NULL DEFAULT '',
				target_bucket_code varchar(191) NOT NULL DEFAULT '',
				dispatch_movement_id bigint(20) unsigned NOT NULL DEFAULT 0,
				receipt_movement_id bigint(20) unsigned NOT NULL DEFAULT 0,
				variance_movement_id bigint(20) unsigned NOT NULL DEFAULT 0,
				override_route varchar(64) NOT NULL DEFAULT '',
				override_reason varchar(191) NOT NULL DEFAULT '',
				override_note longtext NULL,
				override_actor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				override_at datetime NULL DEFAULT NULL,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY transfer_line (transfer_id, line_number),
				KEY transfer_id (transfer_id),
				KEY transfer_uuid (transfer_uuid),
				KEY line_status (line_status),
				KEY product_id (product_id),
				KEY vendor_id (vendor_id),
				KEY source_bucket_id (source_bucket_id),
				KEY target_bucket_id (target_bucket_id),
				KEY dispatch_movement_id (dispatch_movement_id),
				KEY receipt_movement_id (receipt_movement_id),
				KEY variance_movement_id (variance_movement_id),
				KEY override_route (override_route),
				KEY override_actor_id (override_actor_id)
			) {$charset_collate};",
			"CREATE TABLE {$inventory_custody_endpoints_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				endpoint_key varchar(100) NOT NULL DEFAULT '',
				endpoint_name varchar(190) NOT NULL DEFAULT '',
				endpoint_type varchar(32) NOT NULL DEFAULT 'custom',
				endpoint_status varchar(32) NOT NULL DEFAULT 'active',
				node_ref_type varchar(32) NOT NULL DEFAULT '',
				node_ref_id bigint(20) unsigned NOT NULL DEFAULT 0,
				parent_endpoint_id bigint(20) unsigned NOT NULL DEFAULT 0,
				default_route_policy varchar(50) NOT NULL DEFAULT 'guidance',
				allows_direct_collection tinyint(1) NOT NULL DEFAULT 1,
				allows_direct_recovery tinyint(1) NOT NULL DEFAULT 1,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY endpoint_key (endpoint_key),
				KEY endpoint_type (endpoint_type),
				KEY endpoint_status (endpoint_status),
				KEY node_ref_lookup (node_ref_type, node_ref_id),
				KEY parent_endpoint_id (parent_endpoint_id)
			) {$charset_collate};",
			"CREATE TABLE {$inventory_custody_endpoint_relationships_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				source_endpoint_id bigint(20) unsigned NOT NULL DEFAULT 0,
				target_endpoint_id bigint(20) unsigned NOT NULL DEFAULT 0,
				relationship_key varchar(100) NOT NULL DEFAULT '',
				relationship_type varchar(32) NOT NULL DEFAULT 'default_route',
				route_priority int(11) NOT NULL DEFAULT 0,
				route_policy varchar(50) NOT NULL DEFAULT 'guidance',
				is_default_route tinyint(1) NOT NULL DEFAULT 1,
				is_active tinyint(1) NOT NULL DEFAULT 1,
				guidance_label varchar(190) NOT NULL DEFAULT '',
				guidance_notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY endpoint_relationship (source_endpoint_id, target_endpoint_id, relationship_key),
				KEY source_endpoint_id (source_endpoint_id),
				KEY target_endpoint_id (target_endpoint_id),
				KEY relationship_type (relationship_type),
				KEY route_priority (route_priority),
				KEY is_default_route (is_default_route),
				KEY is_active (is_active)
			) {$charset_collate};",
			"CREATE TABLE {$fulfillment_allocations_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				square_sale_id bigint(20) unsigned NOT NULL DEFAULT 0,
				square_order_id varchar(191) NOT NULL DEFAULT '',
				product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				source_bucket_id bigint(20) unsigned DEFAULT NULL,
				source_bucket_code varchar(191) NOT NULL DEFAULT '',
				allocation_type varchar(50) NOT NULL DEFAULT 'event_stock',
				allocation_status varchar(32) NOT NULL DEFAULT 'allocated',
				quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY sale_allocation_identity (square_sale_id, square_order_id, product_id, vendor_id, event_id, allocation_type, source_bucket_code),
				KEY square_sale_id (square_sale_id),
				KEY square_order_id (square_order_id),
				KEY product_id (product_id),
				KEY vendor_id (vendor_id),
				KEY event_id (event_id),
				KEY source_bucket_id (source_bucket_id),
				KEY source_bucket_code (source_bucket_code),
				KEY allocation_type (allocation_type),
				KEY allocation_status (allocation_status)
			) {$charset_collate};",
			"CREATE TABLE {$product_cost_rules_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				assignment_type varchar(20) NOT NULL DEFAULT 'product',
				product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				category_term_id bigint(20) unsigned NOT NULL DEFAULT 0,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				stitch_job_type varchar(50) NOT NULL DEFAULT '',
				unit_cost decimal(20,4) NOT NULL DEFAULT 0.0000,
				stitching_price decimal(20,4) NOT NULL DEFAULT 0.0000,
				is_active tinyint(1) NOT NULL DEFAULT 1,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY assignment_type (assignment_type),
				KEY product_id (product_id),
				KEY category_term_id (category_term_id),
				KEY vendor_id (vendor_id),
				KEY is_active (is_active)
			) {$charset_collate};",
			"CREATE TABLE {$sync_runs_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				source_system varchar(50) NOT NULL DEFAULT '',
				started_at datetime NOT NULL,
				completed_at datetime NULL DEFAULT NULL,
				sync_watermark varchar(64) NOT NULL DEFAULT '',
				success tinyint(1) NOT NULL DEFAULT 0,
				processed_records int(11) unsigned NOT NULL DEFAULT 0,
				skipped_records int(11) unsigned NOT NULL DEFAULT 0,
				error_count int(11) unsigned NOT NULL DEFAULT 0,
				message text NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY source_system (source_system),
				KEY completed_at (completed_at),
				KEY success (success)
			) {$charset_collate};",
			"CREATE TABLE {$sync_actions_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				run_id bigint(20) unsigned NOT NULL,
				external_record_id varchar(191) NOT NULL DEFAULT '',
				action_type varchar(50) NOT NULL DEFAULT '',
				entity_type varchar(50) NOT NULL DEFAULT '',
				entity_id bigint(20) unsigned NOT NULL DEFAULT 0,
				status varchar(20) NOT NULL DEFAULT 'success',
				quantity_delta decimal(20,4) NOT NULL DEFAULT 0.0000,
				message text NULL,
				occurred_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY run_id (run_id),
				KEY external_record_id (external_record_id),
				KEY action_type (action_type),
				KEY entity_type (entity_type),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$sync_effects_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				sync_run_id bigint(20) unsigned NOT NULL DEFAULT 0,
				sync_action_id bigint(20) unsigned NOT NULL DEFAULT 0,
				effect_type varchar(50) NOT NULL DEFAULT '',
				target_table varchar(191) NOT NULL DEFAULT '',
				target_id bigint(20) unsigned NOT NULL DEFAULT 0,
				reversal_status varchar(32) NOT NULL DEFAULT 'active',
				reversed_at datetime NULL DEFAULT NULL,
				reversal_sync_action_id bigint(20) unsigned NOT NULL DEFAULT 0,
				metadata_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY sync_run_id (sync_run_id),
				KEY sync_action_id (sync_action_id),
				KEY target_table_target_id (target_table(64), target_id),
				KEY effect_type (effect_type),
				KEY reversal_status (reversal_status)
			) {$charset_collate};",
			"CREATE TABLE {$square_queue_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				square_order_id varchar(191) NOT NULL DEFAULT '',
				location_id varchar(191) NOT NULL DEFAULT '',
				import_status varchar(32) NOT NULL DEFAULT 'pending',
				payload longtext NULL,
				imported_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY square_order_id (square_order_id),
				KEY location_id (location_id),
				KEY import_status (import_status)
			) {$charset_collate};",
			"CREATE TABLE {$square_raw_events_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				source_type varchar(50) NOT NULL DEFAULT 'webhook',
				square_event_type varchar(100) NOT NULL DEFAULT '',
				square_object_type varchar(100) NOT NULL DEFAULT '',
				square_object_id varchar(191) NOT NULL DEFAULT '',
				dedupe_key varchar(191) NOT NULL DEFAULT '',
				event_version varchar(64) NOT NULL DEFAULT '',
				payload_json longtext NULL,
				received_at datetime NOT NULL,
				processing_status varchar(32) NOT NULL DEFAULT 'pending',
				processing_attempts int(11) unsigned NOT NULL DEFAULT 0,
				sync_run_id bigint(20) unsigned NOT NULL DEFAULT 0,
				error_message text NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY dedupe_key (dedupe_key),
				KEY square_object_id (square_object_id),
				KEY square_event_type (square_event_type),
				KEY processing_status (processing_status),
				KEY sync_run_id (sync_run_id),
				KEY received_at (received_at)
			) {$charset_collate};",
			"CREATE TABLE {$square_team_members_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				square_team_member_id varchar(191) NOT NULL DEFAULT '',
				display_name varchar(191) NOT NULL DEFAULT '',
				given_name varchar(100) NOT NULL DEFAULT '',
				family_name varchar(100) NOT NULL DEFAULT '',
				email_address varchar(190) NOT NULL DEFAULT '',
				phone_number varchar(50) NOT NULL DEFAULT '',
				status varchar(32) NOT NULL DEFAULT 'active',
				raw_payload_json longtext NULL,
				last_synced_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY square_team_member_id (square_team_member_id),
				KEY email_address (email_address),
				KEY phone_number (phone_number),
				KEY status (status),
				KEY last_synced_at (last_synced_at)
			) {$charset_collate};",
			"CREATE TABLE {$runtime_assignments_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				request_id bigint(20) unsigned NOT NULL DEFAULT 0,
				source_assignment_id bigint(20) unsigned NOT NULL DEFAULT 0,
				square_team_member_id varchar(191) NOT NULL DEFAULT '',
				square_location_id varchar(191) NOT NULL DEFAULT '',
				starts_at datetime NULL DEFAULT NULL,
				ends_at datetime NULL DEFAULT NULL,
				status varchar(32) NOT NULL DEFAULT 'pending',
				assignment_mode varchar(32) NOT NULL DEFAULT 'fcfs',
				manual_override_flag tinyint(1) NOT NULL DEFAULT 0,
				priority int(11) NOT NULL DEFAULT 0,
				commission_rate decimal(7,4) NOT NULL DEFAULT 0.0000,
				active_for_import tinyint(1) NOT NULL DEFAULT 1,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY vendor_id (vendor_id),
				KEY event_id (event_id),
				KEY request_id (request_id),
				KEY source_assignment_id (source_assignment_id),
				KEY square_location_window (square_location_id, starts_at, ends_at),
				KEY square_team_window (square_team_member_id, starts_at, ends_at),
				KEY status (status),
				KEY active_for_import (active_for_import),
				KEY priority (priority)
			) {$charset_collate};",
			"CREATE TABLE {$square_normalized_sales_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				square_order_id varchar(191) NOT NULL DEFAULT '',
				square_line_item_uid varchar(191) NOT NULL DEFAULT '',
				square_payment_id varchar(191) NOT NULL DEFAULT '',
				square_location_id varchar(191) NOT NULL DEFAULT '',
				square_team_member_id varchar(191) NOT NULL DEFAULT '',
				occurred_at datetime NULL DEFAULT NULL,
				gross_sales decimal(20,2) NOT NULL DEFAULT 0.00,
				tax_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				discount_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				tip_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				refund_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				net_sales decimal(20,2) NOT NULL DEFAULT 0.00,
				currency varchar(10) NOT NULL DEFAULT 'USD',
				source_raw_event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				source_queue_id bigint(20) unsigned NOT NULL DEFAULT 0,
				normalization_status varchar(32) NOT NULL DEFAULT 'normalized',
				payload_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY square_line (square_order_id, square_line_item_uid),
				KEY square_payment_id (square_payment_id),
				KEY square_location_id (square_location_id),
				KEY square_team_member_id (square_team_member_id),
				KEY occurred_at (occurred_at),
				KEY source_raw_event_id (source_raw_event_id),
				KEY source_queue_id (source_queue_id),
				KEY normalization_status (normalization_status)
			) {$charset_collate};",
			"CREATE TABLE {$sales_exceptions_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				normalized_sale_id bigint(20) unsigned NOT NULL DEFAULT 0,
				exception_type varchar(50) NOT NULL DEFAULT '',
				severity varchar(20) NOT NULL DEFAULT 'warning',
				message text NULL,
				resolution_status varchar(32) NOT NULL DEFAULT 'open',
				resolved_by bigint(20) unsigned NOT NULL DEFAULT 0,
				resolved_at datetime NULL DEFAULT NULL,
				resolution_notes text NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY normalized_sale_id (normalized_sale_id),
				KEY exception_type (exception_type),
				KEY severity (severity),
				KEY resolution_status (resolution_status),
				KEY resolved_by (resolved_by),
				KEY resolved_at (resolved_at)
			) {$charset_collate};",
			"CREATE TABLE {$vendor_sales_attribution_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				normalized_sale_id bigint(20) unsigned NOT NULL DEFAULT 0,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				runtime_assignment_id bigint(20) unsigned NOT NULL DEFAULT 0,
				attribution_status varchar(32) NOT NULL DEFAULT 'pending',
				gross_sales decimal(20,2) NOT NULL DEFAULT 0.00,
				tax_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				discount_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				tip_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				refund_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				net_sales_authoritative decimal(20,2) NOT NULL DEFAULT 0.00,
				commissionable_sales decimal(20,2) NOT NULL DEFAULT 0.00,
				commission_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				payout_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				calculated_at datetime NULL DEFAULT NULL,
				source_sync_run_id bigint(20) unsigned NOT NULL DEFAULT 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY normalized_sale_id (normalized_sale_id),
				KEY vendor_id (vendor_id),
				KEY event_id (event_id),
				KEY runtime_assignment_id (runtime_assignment_id),
				KEY attribution_status (attribution_status),
				KEY source_sync_run_id (source_sync_run_id),
				KEY calculated_at (calculated_at)
			) {$charset_collate};",
			"CREATE TABLE {$square_sales_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				square_order_id varchar(191) NOT NULL DEFAULT '',
				square_line_item_uid varchar(191) NOT NULL DEFAULT '',
				square_location_id varchar(191) NOT NULL DEFAULT '',
				square_customer_id varchar(191) NOT NULL DEFAULT '',
				customer_id bigint(20) unsigned NOT NULL DEFAULT 0,
				shipping_address_id bigint(20) unsigned NOT NULL DEFAULT 0,
				billing_address_id bigint(20) unsigned NOT NULL DEFAULT 0,
				vendor_id bigint(20) unsigned NOT NULL DEFAULT 0,
				event_id bigint(20) unsigned NOT NULL DEFAULT 0,
				woo_order_id bigint(20) unsigned NOT NULL DEFAULT 0,
				woo_product_id bigint(20) unsigned NOT NULL DEFAULT 0,
				sku varchar(191) NOT NULL DEFAULT '',
				source varchar(50) NOT NULL DEFAULT 'square',
				delivery_method varchar(32) NOT NULL DEFAULT 'pickup',
				shipping_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				discount_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				discount_label varchar(191) NOT NULL DEFAULT '',
				tip_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				tax_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				amount_paid decimal(20,2) NOT NULL DEFAULT 0.00,
				fulfillment_status varchar(32) NOT NULL DEFAULT 'pending',
				quantity decimal(20,4) NOT NULL DEFAULT 0.0000,
				gross_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				net_amount decimal(20,2) NOT NULL DEFAULT 0.00,
				payload longtext NULL,
				sold_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY square_line (square_order_id, square_line_item_uid),
				KEY square_location_id (square_location_id),
				KEY square_customer_id (square_customer_id),
				KEY customer_id (customer_id),
				KEY shipping_address_id (shipping_address_id),
				KEY billing_address_id (billing_address_id),
				KEY vendor_id (vendor_id),
				KEY event_id (event_id),
				KEY woo_order_id (woo_order_id),
				KEY woo_product_id (woo_product_id),
				KEY sku (sku),
				KEY delivery_method (delivery_method),
				KEY shipping_amount (shipping_amount),
				KEY discount_amount (discount_amount),
				KEY tip_amount (tip_amount),
				KEY tax_amount (tax_amount),
				KEY amount_paid (amount_paid),
				KEY fulfillment_status (fulfillment_status),
				KEY sold_at (sold_at)
			) {$charset_collate};",
			"CREATE TABLE {$event_reconciliations_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				event_id bigint(20) unsigned NOT NULL,
				reconciliation_type varchar(32) NOT NULL DEFAULT 'planned',
				snapshot_date datetime NOT NULL,
				planned_inventory_qty decimal(20,4) NOT NULL DEFAULT 0.0000,
				actual_inventory_qty decimal(20,4) NOT NULL DEFAULT 0.0000,
				expected_sales_total decimal(20,2) NOT NULL DEFAULT 0.00,
				actual_sales_total decimal(20,2) NOT NULL DEFAULT 0.00,
				expected_expense_total decimal(20,2) NOT NULL DEFAULT 0.00,
				actual_expense_total decimal(20,2) NOT NULL DEFAULT 0.00,
				discrepancy_status varchar(32) NOT NULL DEFAULT 'pending',
				discrepancy_count int(11) NOT NULL DEFAULT 0,
				notes longtext NULL,
				reconciled_by bigint(20) unsigned DEFAULT NULL,
				reconciled_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY event_id (event_id),
				KEY reconciliation_type (reconciliation_type),
				KEY snapshot_date (snapshot_date),
				KEY discrepancy_status (discrepancy_status),
				KEY reconciled_at (reconciled_at)
			) {$charset_collate};",
			"CREATE TABLE {$event_reconciliation_discrepancies_table} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				reconciliation_id bigint(20) unsigned NOT NULL,
				event_id bigint(20) unsigned NOT NULL,
				discrepancy_type varchar(50) NOT NULL DEFAULT 'inventory',
				reference_type varchar(50) NOT NULL DEFAULT 'bucket_assignment',
				reference_id varchar(191) NOT NULL DEFAULT '',
				expected_value decimal(20,4) NOT NULL DEFAULT 0.0000,
				actual_value decimal(20,4) NOT NULL DEFAULT 0.0000,
				variance_amount decimal(20,4) NOT NULL DEFAULT 0.0000,
				severity varchar(20) NOT NULL DEFAULT 'info',
				variance_percent decimal(7,4) NOT NULL DEFAULT 0.0000,
				resolution_notes longtext NULL,
				resolved_by bigint(20) unsigned DEFAULT NULL,
				resolved_at datetime NULL DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY reconciliation_id (reconciliation_id),
				KEY event_id (event_id),
				KEY discrepancy_type (discrepancy_type),
				KEY reference_type (reference_type),
				KEY reference_id (reference_id),
				KEY severity (severity),
				KEY resolved_at (resolved_at)
			) {$charset_collate};",
		);
	}

	public function drop_tables(): void {
		global $wpdb;

		foreach ( $this->get_table_names() as $table_name ) {
			$wpdb->query( "DROP TABLE IF EXISTS `{$table_name}`" ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
		}
	}
}
