using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MustaineAI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816123000_AddArtworkSubcategories")]
    public partial class AddArtworkSubcategories : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "ArtworkSubcategories"
                (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ArtworkKey" character varying(300) NOT NULL,
                    "ArtworkName" character varying(300) NOT NULL,
                    "Subcategory" character varying(80) NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_ArtworkSubcategories_ArtworkKey"
                ON "ArtworkSubcategories" ("ArtworkKey");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ArtworkSubcategories");
        }
    }
}
