// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MustaineAI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815210000_AddSquareShowOrderCapture")]
    partial class AddSquareShowOrderCapture
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
